# Danish translations for ceilometer.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
# Jens Hyllegaard <jens.hyllegaard@gmail.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version:  Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2013-10-02 06:02+0000\n"
"PO-Revision-Date: 2013-05-16 08:53+0000\n"
"Last-Translator: Jens Hyllegaard <jens.hyllegaard@gmail.com>\n"
"Language-Team: Danish "
"(http://www.transifex.com/projects/p/openstack/language/da/)\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/alarm/rpc.py:51
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: ceilometer/alarm/service.py:96
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:101
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:106
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: ceilometer/alarm/service.py:110
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:233
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:242
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:252
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:271
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:67
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:79
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:47
#, python-format
msgid "%(missing_states)d alarms in %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:60
#, python-format
msgid ""
"Transition to %(state)s due at least to one alarm in %(alarm_ids)s in "
"state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:64
#, python-format
msgid ""
"Remaining as %(state)s due at least to one alarm in %(alarm_ids)s in "
"state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:70
#, python-format
msgid ""
"Transition to %(state)s due to all alarms (%(alarm_ids)s) in state "
"%(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:74
#, python-format
msgid ""
"Remaining as %(state)s due to all alarms (%(alarm_ids)s) in state "
"%(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:58
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:71
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:75
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:80
#, python-format
msgid "stats query %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:86
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:95
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:108
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(last)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:112
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(last)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:162
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:132
#, python-format
msgid "triggering %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:133
#, python-format
msgid "known evaluators %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:136
#, python-format
msgid "per evaluator allocation %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:146
#, python-format
msgid ""
"%(this)s bailing on distribution cycle as older partition detected: "
"%(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:152
#, python-format
msgid "%(verb)s-ing %(alloc)s to %(eval)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:156
#, python-format
msgid "master taking %s for self"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:174
#, python-format
msgid "newly deleted alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:177
msgid "alarm deletion activity requires rebalance"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:202
#, python-format
msgid "%s still warming up"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:207
#, python-format
msgid "last heard from %(report)s %(delta)s seconds ago"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:212
#, python-format
msgid "%(this)s detects stale evaluator: %(stale)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:217
#, python-format
msgid "%(this)s sees older potential master: %(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:219
#, python-format
msgid "%(this)s is master?: %(is_master)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:232
#, python-format
msgid "newly created alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:253
#, python-format
msgid "%s checking mastership status"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:260
msgid "mastership check failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:270
#, python-format
msgid "%(this)s knows about %(reports)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:276
#, python-format
msgid "%(this)s got assignment: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:283
#, python-format
msgid "%(this)s got allocation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:289
#, python-format
msgid "%s reporting presence"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:293
msgid "presence reporting failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:298
#, python-format
msgid "%s has no assigned alarms to evaluate"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:302
#, python-format
msgid "%(this)s alarms for evaluation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:308
msgid "assignment retrieval failed"
msgstr ""

#: ceilometer/api/controllers/v2.py:73
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2.py:91
#, python-format
msgid "Value %(value)s is invalid (should be greater or equal to %(min)s)"
msgstr ""

#: ceilometer/api/controllers/v2.py:97
#, python-format
msgid "Value %(value)s is invalid (should be lower or equal to %(max)s)"
msgstr ""

#: ceilometer/api/controllers/v2.py:235
#, python-format
msgid "Failed to convert the metadata value %s automatically"
msgstr ""

#: ceilometer/api/controllers/v2.py:253
#, python-format
msgid ""
"Failed to convert the metadata value %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:258
#, python-format
msgid ""
"The data type %s is not supported. The supported data type list is: "
"integer, float, boolean and string."
msgstr ""

#: ceilometer/api/controllers/v2.py:263
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:728
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2.py:890
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2.py:948
#, python-format
msgid "threshold_rule/%s is mandatory"
msgstr ""

#: ceilometer/api/controllers/v2.py:966
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/api/controllers/v2.py:1005
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1022
msgid "combination_rule/alarm_ids is mandatory"
msgstr ""

#: ceilometer/api/controllers/v2.py:1031
#, python-format
msgid "Alarm %s doesn't exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:1120
#, python-format
msgid "%s is mandatory"
msgstr ""

#: ceilometer/api/controllers/v2.py:1125
msgid "threshold_rule and combination_rule cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2.py:1223
msgid "Alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1280 ceilometer/api/controllers/v2.py:1407
msgid "Alarm incorrect"
msgstr "Alarm er forkert"

#: ceilometer/api/controllers/v2.py:1325
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2.py:1399
msgid "Alarm with that name exists"
msgstr "Alarm med dette navn findes"

#: ceilometer/collector/service.py:100
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector/service.py:112
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/compute/nova_notifier.py:84
#, python-format
msgid "using provided stats gatherer %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:87
msgid "making a new stats gatherer"
msgstr ""

#: ceilometer/compute/nova_notifier.py:114
#, python-format
msgid "INFO %r"
msgstr "INFO %r"

#: ceilometer/compute/nova_notifier.py:146
#, python-format
msgid "ignoring %s"
msgstr "ignorerer %s"

#: ceilometer/compute/nova_notifier.py:148
#, python-format
msgid "processing %s"
msgstr "behandler %s"

#: ceilometer/compute/nova_notifier.py:152
#, python-format
msgid "polling final stats for %r"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:164
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:166
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/energy/kwapi.py:77
msgid "Kwapi endpoint not found"
msgstr ""

#: ceilometer/objectstore/swift.py:67
msgid "Swift endpoint not found"
msgstr ""

#: ceilometer/openstack/common/eventlet_backdoor.py:142
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: ceilometer/openstack/common/exception.py:103
msgid "Uncaught exception"
msgstr ""

#: ceilometer/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: ceilometer/openstack/common/excutils.py:90
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: ceilometer/openstack/common/fileutils.py:64
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:100
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:166
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:175
#, python-format
msgid "Attempting to grab file lock \"%(lock)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:185
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:203
#, python-format
msgid "Got file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:207
#, python-format
msgid "Released file lock \"%(lock)s\" at %(path)s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:244
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:248
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: ceilometer/openstack/common/log.py:244
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:336
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ceilometer/openstack/common/log.py:386
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "syslog faciliteten skal være en af: %s"

#: ceilometer/openstack/common/log.py:556
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Fatalt kald til forældet konfig: %(msg)s"

#: ceilometer/openstack/common/loopingcall.py:84
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:91
msgid "in fixed duration looping call"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:131
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr ""

#: ceilometer/openstack/common/policy.py:75
msgid "JSON file containing policy"
msgstr ""

#: ceilometer/openstack/common/policy.py:78
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: ceilometer/openstack/common/policy.py:92
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: ceilometer/openstack/common/policy.py:177
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: ceilometer/openstack/common/policy.py:207
msgid "Rules successfully reloaded"
msgstr ""

#: ceilometer/openstack/common/policy.py:253
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: ceilometer/openstack/common/policy.py:268
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: ceilometer/openstack/common/policy.py:478
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: ceilometer/openstack/common/policy.py:488
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: ceilometer/openstack/common/policy.py:759
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: ceilometer/openstack/common/service.py:136
#: ceilometer/openstack/common/service.py:346
msgid "Full set of CONF:"
msgstr ""

#: ceilometer/openstack/common/service.py:143
#: ceilometer/openstack/common/service.py:228
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: ceilometer/openstack/common/service.py:155
msgid "Exception during rpc cleanup."
msgstr ""

#: ceilometer/openstack/common/service.py:200
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: ceilometer/openstack/common/service.py:234
msgid "Unhandled exception"
msgstr "Ubehandlet undtagelse"

#: ceilometer/openstack/common/service.py:267
msgid "Forking too fast, sleeping"
msgstr ""

#: ceilometer/openstack/common/service.py:289
#, python-format
msgid "Started child %d"
msgstr ""

#: ceilometer/openstack/common/service.py:299
#, python-format
msgid "Starting %d workers"
msgstr ""

#: ceilometer/openstack/common/service.py:316
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: ceilometer/openstack/common/service.py:320
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: ceilometer/openstack/common/service.py:324
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: ceilometer/openstack/common/service.py:354
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: ceilometer/openstack/common/service.py:372
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:52
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:55
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:58
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:61
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:100
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:88
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:184
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:191
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: ceilometer/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr "Ugyldig parameter: Unicode er ikke understøttet af den aktuelle database."

#: ceilometer/openstack/common/db/sqlalchemy/session.py:542
msgid "DB exception wrapped."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:604
#, python-format
msgid "Got mysql server has gone away: %s"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:684
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:50
msgid "Sort key supplied was not valid."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:89
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:111
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:182
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:188
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:268
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:290
msgid "Unsupported id columns type"
msgstr ""

#: ceilometer/openstack/common/middleware/notifier.py:40
#, python-format
msgid "An exception occurred processing the API call: %s "
msgstr ""

#: ceilometer/openstack/common/middleware/sizelimit.py:57
#: ceilometer/openstack/common/middleware/sizelimit.py:66
#: ceilometer/openstack/common/middleware/sizelimit.py:77
msgid "Request is too large."
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:129
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:145
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:164
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: ceilometer/openstack/common/notifier/rpc_notifier.py:45
#: ceilometer/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: ceilometer/openstack/common/rpc/__init__.py:106
#, python-format
msgid ""
"A RPC is being made while holding a lock. The locks currently held are "
"%(locks)s. This is probably a bug. Please report it. Include the "
"following: [%(stack)s]."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshhold: %d. There "
"could be a MulticallProxyWaiter leak."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:341
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:434
#, python-format
msgid "received %s"
msgstr "modtog %s"

#: ceilometer/openstack/common/rpc/amqp.py:442
#, python-format
msgid "no method for message: %s"
msgstr "ingen metode for beskeden: %s"

#: ceilometer/openstack/common/rpc/amqp.py:443
#, python-format
msgid "No method for message: %s"
msgstr "Ingen metode for beskeden: %s"

#: ceilometer/openstack/common/rpc/amqp.py:471
#: ceilometer/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:479
#: ceilometer/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:553
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:556
#, python-format
msgid "MSG_ID is %s"
msgstr "MSG_ID er %s"

#: ceilometer/openstack/common/rpc/amqp.py:582
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:591
msgid "Making asynchronous fanout cast..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:619
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:77
msgid "An unknown RPC related exception occurred."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:89
msgid "Exception in string format operation"
msgstr "Undtagelse i streng-format handlingen"

#: ceilometer/openstack/common/rpc/common.py:107
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:124
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:141
#: ceilometer/openstack/common/rpc/common.py:142
#: ceilometer/openstack/common/rpc/common.py:143
msgid "<unknown>"
msgstr "<ukendt>"

#: ceilometer/openstack/common/rpc/common.py:147
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:151
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:155
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:160
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:165
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:289
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:157
msgid "Failed to process message ... skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:161
msgid "Failed to process message ... will requeue."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:496
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:518
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:555
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:569
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:623
#: ceilometer/openstack/common/rpc/impl_qpid.py:585
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:641
#: ceilometer/openstack/common/rpc/impl_qpid.py:600
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:645
#: ceilometer/openstack/common/rpc/impl_qpid.py:604
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:684
#: ceilometer/openstack/common/rpc/impl_qpid.py:639
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:89
#, python-format
msgid "Invalid value for qpid_topology_version: %d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:527
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:533
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:546
msgid "Re-established AMQP queues"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:612
msgid "Error processing message.  Skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr "Udpakker svar"

#: ceilometer/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr "%(msg)s"

#: ceilometer/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr "Sender besked(er) til: %s"

#: ceilometer/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:47
msgid "Match not found by MatchMaker."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:81
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:217
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:229
msgid "Register before starting heartbeat."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker_ring.py:77
#: ceilometer/openstack/common/rpc/matchmaker_ring.py:95
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: ceilometer/openstack/common/rpc/service.py:49
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: ceilometer/publisher/udp.py:55
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr ""

#: ceilometer/publisher/udp.py:62
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/impl_db2.py:404 ceilometer/storage/impl_db2.py:473
#: ceilometer/storage/impl_db2.py:681 ceilometer/storage/impl_hbase.py:308
#: ceilometer/storage/impl_hbase.py:392 ceilometer/storage/impl_mongodb.py:605
#: ceilometer/storage/impl_mongodb.py:687
#: ceilometer/storage/impl_mongodb.py:863
#: ceilometer/storage/impl_sqlalchemy.py:296
#: ceilometer/storage/impl_sqlalchemy.py:395
#: ceilometer/storage/impl_sqlalchemy.py:610
msgid "Pagination not implemented"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:114
msgid "Missing required meter specifier"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:137
#: ceilometer/storage/impl_sqlalchemy.py:298
#: ceilometer/storage/impl_sqlalchemy.py:397
msgid "metaquery not implemented"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:544
msgid "Unable to group by these fields"
msgstr ""

#: ceilometer/transformer/conversions.py:67
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr ""

#: ceilometer/transformer/conversions.py:104
#: ceilometer/transformer/conversions.py:144
#, python-format
msgid "converted to: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:146
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

#~ msgid "Got semaphore \"%(lock)s\" for method \"%(method)s\"..."
#~ msgstr ""

#~ msgid "Attempting to grab file lock \"%(lock)s\" for method \"%(method)s\"..."
#~ msgstr ""

#~ msgid "Got file lock \"%(lock)s\" at %(path)s for method \"%(method)s\"..."
#~ msgstr ""

#~ msgid ""
#~ msgstr ""

#~ msgid "Unable to parse action %(action)s for alarm %(alarm)s"
#~ msgstr ""

#~ msgid "Action %(scheme)s for alarm %(alarm)s is unknown, cannot notify"
#~ msgstr ""

#~ msgid "Failed to understand rule %(rule)r"
#~ msgstr ""

#~ msgid "Got unknown keyword args to utils.execute: %r"
#~ msgstr ""

#~ msgid "Running cmd (subprocess): %s"
#~ msgstr ""

#~ msgid "Result was %s"
#~ msgstr "Resultatet var %s"

#~ msgid "%r failed. Retrying."
#~ msgstr "%r mislykkedes. Prøver igen."

#~ msgid "Running cmd (SSH): %s"
#~ msgstr ""

#~ msgid "Environment not supported over SSH"
#~ msgstr ""

#~ msgid "process_input not supported over SSH"
#~ msgstr ""

#~ msgid "Problem '%(e)s' attempting to send to notification driver %(driver)s."
#~ msgstr ""

#~ msgid "The rabbit_notifier is now deprecated. Please use rpc_notifier instead."
#~ msgstr ""

#~ msgid "Failed to sanitize %(item)s. Key error %(err)s"
#~ msgstr ""

#~ msgid "version should be an integer"
#~ msgstr ""

#~ msgid "Publishing counter %(msg)s over UDP to %(host)s:%(port)d"
#~ msgstr ""

#~ msgid "Unable to send counter over UDP"
#~ msgstr ""

#~ msgid "dropping counter with no predecessor: %s"
#~ msgstr ""

#~ msgid "Unable to store events: %s"
#~ msgstr ""

#~ msgid "skipping alarm %s"
#~ msgstr ""

#~ msgid "threshold evaluation cycle failed"
#~ msgstr ""

#~ msgid "skipping alarm %s: alarm disabled"
#~ msgstr ""

#~ msgid "Unknown resource"
#~ msgstr ""

#~ msgid "Unknown alarm"
#~ msgstr "Ukendt alarm"

