# SeYeon Lee <sy_lee@kr.ibm.com>, 2016. #zanata
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 6.0.0.0rc2.dev1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2016-03-20 20:02+0000\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"PO-Revision-Date: 2016-03-21 03:28+0000\n"
"Last-Translator: SeYeon Lee <sy_lee@kr.ibm.com>\n"
"Language-Team: Korean (South Korea)\n"
"Language: ko-KR\n"
"X-Generator: Zanata 3.7.3\n"
"Plural-Forms: nplurals=1; plural=0\n"

#, python-format
msgid "Cannot load inspector %(name)s: %(err)s"
msgstr "%(name)s 검사기를 로드할 수 없음: %(err)s"

#, python-format
msgid "Could not get Resident Memory Usage for %(id)s: %(e)s"
msgstr "%(id)s의 상주 메모리 사용을 가져올 수 없음 : %(e)s"

#, python-format
msgid "Dispatcher failed to handle the %s, requeue it."
msgstr "디스패처에서 %s을(를) 처리하지 못하여 다시 대기열에 둡니다."

msgid "Error connecting to coordination backend."
msgstr "조정 백엔드에 연결하는 중에 오류가 발생했습니다."

msgid "Error getting group membership info from coordination backend."
msgstr "조정 백엔드에서 그룹 멤버십 정보를 가져오는 중에 오류가 발생했습니다."

#, python-format
msgid "Error joining partitioning group %s, re-trying"
msgstr ""
"파티션 지정 그룹 %s을(를) 결합하는 중에 오류가 발생하여, 다시 시도 중입니다."

#, python-format
msgid "Error loading meter definition : %(err)s"
msgstr "미터 정의 로드 오류 : %(err)s"

#, python-format
msgid "Error processing event and it will be dropped: %s"
msgstr "이벤트 처리 중 오류가 발생하므로 삭제됨: %s"

msgid "Error sending a heartbeat to coordination backend."
msgstr "하트비트를 조정 백엔드에 보내는 중에 오류가 발생했습니다."

msgid "Fail to process a notification"
msgstr "알림을 처리하는 데 실패"

msgid "Fail to process notification"
msgstr "알림을 처리하는 데 실패"

msgid "Failed to connect to Gnocchi."
msgstr "Gnocchi에 연결하지 못했습니다."

#, python-format
msgid "Failed to connect to Kafka service: %s"
msgstr "Kafka 서비스에 연결하는 데 실패: %s"

#, python-format
msgid "Failed to connect to db, purpose %(purpose)s re-try later: %(err)s"
msgstr "db에 연결하는 데 실패, %(purpose)s 용도를 나중에 다시 시도: %(err)s"

#, python-format
msgid "Failed to connect to db, purpose %(purpose)s retry later: %(err)s"
msgstr "db에 연결하는 데 실패, %(purpose)s 용도를 나중에 다시 시도: %(err)s"

#, python-format
msgid "Failed to load resource due to error %s"
msgstr "%s 오류로 인해 자원을 로드하는 데 실패"

#, python-format
msgid "Failed to record event: %s"
msgstr "이벤트를 기록하는 데 실패: %s"

#, python-format
msgid "Failed to record metering data: %s"
msgstr "측정 데이터 기록 실패: %s"

msgid "Failed to retry to send sample data with max_retry times"
msgstr "샘플 데이터를 max_retry 횟수만큼 보내는 데 실패"

msgid ""
"Group ID: %{group_id}s, Members: %{members}s, Me: %{me}s: Current agent is "
"not part of group and cannot take tasks"
msgstr ""
"그룹 ID: %{group_id}s, 멤버: %{members}s, 사용자: %{me}s: 현재 에이전트가 그"
"룹의 일부가 아니므로 작업을 수행할 수 없음"

#, python-format
msgid "Invalid type %s specified"
msgstr "올바르지 않은 유형 %s이(가) 지정됨"

#, python-format
msgid "Missing field %s"
msgstr "%s 필드 누락"

msgid "Passed resource dict must contain keys resource_id and resource_url."
msgstr "전달된 자원 dict에 키 resource_id와 resource_url이 포함되어야 합니다."

#, python-format
msgid "Required field %(field)s should be a %(type)s"
msgstr "필수 필드 %(field)s은(는) %(type)s이어야 함"

#, python-format
msgid "Required field %s not specified"
msgstr "필수 필드 %s이(가) 지정되지 않음"

#, python-format
msgid "Required fields %s not specified"
msgstr "필수 필드 %s이(가) 지정되지 않음"

#, python-format
msgid "Skip invalid resource %s"
msgstr "올바르지 않은 자원 %s 건너뛰기"

#, python-format
msgid "Skipping %(name)s, keystone issue: %(exc)s"
msgstr "%(name)s 건너뛰기, keystone 문제: %(exc)s"

msgid "Status Code: %{code}s. Failed todispatch event: %{event}s"
msgstr "상태 코드: %{code}s. 이벤트를 디스패치하는 데 실패: %{event}s"

#, python-format
msgid "Unable to load changed event pipeline: %s"
msgstr "변경된 이벤트 파이프라인을 로드할 수 없음: %s"

#, python-format
msgid "Unable to load changed pipeline: %s"
msgstr "변경된 파이프라인을 로드할 수 없음: %s"

#, python-format
msgid "Unrecognized type value %s"
msgstr "인식되지 않은 유형 값 %s"

#, python-format
msgid "inspector call failed for %(ident)s host %(host)s: %(err)s"
msgstr "%(ident)s 호스트 %(host)s의 검사기 호출에 실패: %(err)s"
