# Filipino translations for ceilometer.
# Copyright (C) 2013 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version:  Ceilometer\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-03-31 06:07+0000\n"
"PO-Revision-Date: 2013-10-01 03:40+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Filipino "
"(http://www.transifex.com/projects/p/openstack/language/fil/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/agent.py:84
#, python-format
msgid "Polling pollster %s"
msgstr ""

#: ceilometer/agent.py:94
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent.py:169
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent.py:171
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/cli.py:119
msgid "Clearing expired metering data"
msgstr ""

#: ceilometer/cli.py:124
msgid "Nothing to clean, database time to live is disabled"
msgstr ""

#: ceilometer/collector.py:77
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:80
#, python-format
msgid "UDP: Storing %s"
msgstr ""

#: ceilometer/collector.py:84
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/notification.py:70
msgid "Loading event definitions"
msgstr ""

#: ceilometer/notification.py:82 ceilometer/notifier.py:47
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/notification.py:100
#, python-format
msgid "Event types from %(name)s: %(type)s (ack_on_error=%(error)s)"
msgstr ""

#: ceilometer/notification.py:116
#, python-format
msgid "Could not join consumer pool %(topic)s/%(exchange)s"
msgstr ""

#: ceilometer/notification.py:128
#, python-format
msgid "notification %r"
msgstr ""

#: ceilometer/notification.py:145
#, python-format
msgid "Saving event \"%s\""
msgstr ""

#: ceilometer/notifier.py:40
#, python-format
msgid "loading notification handlers from %s"
msgstr ""

#: ceilometer/pipeline.py:237
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:256
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr ""

#: ceilometer/pipeline.py:269
#, python-format
msgid "Pipeline %(pipeline)s: Sample dropped by transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:276
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:296
#, python-format
msgid "Pipeline %(pipeline)s: Transform sample %(smp)s from %(trans)s transformer"
msgstr ""

#: ceilometer/pipeline.py:306
#, python-format
msgid "Pipeline %s: Publishing samples"
msgstr ""

#: ceilometer/pipeline.py:311
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:315
#, python-format
msgid "Pipeline %s: Published samples"
msgstr ""

#: ceilometer/pipeline.py:331
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:492
msgid "detected decoupled pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:502
msgid "detected deprecated pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:522
#, python-format
msgid "Pipeline config file: %s"
msgstr ""

#: ceilometer/pipeline.py:528
#, python-format
msgid "Pipeline config: %s"
msgstr ""

#: ceilometer/service.py:111
#, python-format
msgid "loading dispatchers from %s"
msgstr ""

#: ceilometer/service.py:119
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr ""

#: ceilometer/service.py:127
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: ceilometer/alarm/rpc.py:52
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: ceilometer/alarm/service.py:92
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:97
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:102
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: ceilometer/alarm/service.py:106
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:153 ceilometer/alarm/service.py:211
msgid "initialize_service_hooks"
msgstr ""

#: ceilometer/alarm/service.py:224
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:233
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:239
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr ""

#: ceilometer/alarm/service.py:244
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:264
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:71
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:83
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:37
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:51
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:74
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:78
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:100
#: ceilometer/alarm/evaluator/threshold.py:177
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:63
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:74
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:83
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:92
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:97
#, python-format
msgid "stats query %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:103
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:112
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:136
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:140
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:196
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: ceilometer/alarm/notifier/log.py:32 ceilometer/alarm/notifier/rest.py:58
#, python-format
msgid ""
"Notifying alarm %(alarm_id)s from %(previous)s to %(current)s with action"
" %(action)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:132
#, python-format
msgid "triggering %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:133
#, python-format
msgid "known evaluators %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:136
#, python-format
msgid "per evaluator allocation %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:146
#, python-format
msgid ""
"%(this)s bailing on distribution cycle as older partition detected: "
"%(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:152
#, python-format
msgid "%(verb)s-ing %(alloc)s to %(eval)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:156
#, python-format
msgid "master taking %s for self"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:174
#, python-format
msgid "newly deleted alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:177
msgid "alarm deletion activity requires rebalance"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:202
#, python-format
msgid "%s still warming up"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:207
#, python-format
msgid "last heard from %(report)s %(delta)s seconds ago"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:212
#, python-format
msgid "%(this)s detects stale evaluator: %(stale)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:217
#, python-format
msgid "%(this)s sees older potential master: %(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:219
#, python-format
msgid "%(this)s is master?: %(is_master)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:232
#, python-format
msgid "newly created alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:243
#, python-format
msgid "%(this)s not overtaken as master? %(still_ahead)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:253
#, python-format
msgid "%s checking mastership status"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:260
msgid "mastership check failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:270
#, python-format
msgid "%(this)s knows about %(reports)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:276
#, python-format
msgid "%(this)s got assignment: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:283
#, python-format
msgid "%(this)s got allocation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:289
#, python-format
msgid "%s reporting presence"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:293
msgid "presence reporting failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:298
#, python-format
msgid "%s has no assigned alarms to evaluate"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:302
#, python-format
msgid "%(this)s alarms for evaluation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:308
msgid "assignment retrieval failed"
msgstr ""

#: ceilometer/api/app.py:133
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: ceilometer/api/app.py:134
msgid "Configuration:"
msgstr ""

#: ceilometer/api/app.py:138
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: ceilometer/api/app.py:142
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: ceilometer/api/middleware.py:112
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:86
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2.py:245
#, python-format
msgid "Failed to convert the metadata value %s automatically"
msgstr ""

#: ceilometer/api/controllers/v2.py:257
#, python-format
msgid "Failed to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:262
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:267
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:278
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:737 ceilometer/api/v1/blueprint.py:579
msgid "clamping min timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:742 ceilometer/api/v1/blueprint.py:582
msgid "clamping max timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:818 ceilometer/api/controllers/v2.py:1074
msgid "Limit must be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:896
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2.py:908
#, python-format
msgid "computed value coming from %r"
msgstr ""

#: ceilometer/api/controllers/v2.py:1090
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2.py:1272
msgid "Limit should be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:1364
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2.py:1365
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1451
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2.py:1525
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/api/controllers/v2.py:1566
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1618
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: ceilometer/api/controllers/v2.py:1739 ceilometer/api/controllers/v2.py:1855
msgid "Alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1743
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: ceilometer/api/controllers/v2.py:1753
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1757
msgid "threshold_rule and combination_rule cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2.py:1924
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:1932
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1933 ceilometer/api/controllers/v2.py:2081
msgid "Alarm incorrect"
msgstr ""

#: ceilometer/api/controllers/v2.py:1983
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2.py:2074
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:2080
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2231
#, python-format
msgid "operator %s not supported"
msgstr ""

#: ceilometer/api/controllers/v2.py:2252
#, python-format
msgid "Getting traits for %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2316
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2.py:2319
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/api/v1/blueprint.py:569
#, python-format
msgid ""
"start_timestamp %(start_timestamp)s, end_timestamp %(end_timestamp)s, "
"min_ts %(min_ts)s, max_ts %(max_ts)s"
msgstr ""

#: ceilometer/central/manager.py:48
#, python-format
msgid "Skip interval_task because Keystone error: %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:82
#, python-format
msgid "using provided stats gatherer %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:85
msgid "making a new stats gatherer"
msgstr ""

#: ceilometer/compute/nova_notifier.py:114
#, python-format
msgid "INFO %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:147
#, python-format
msgid "ignoring %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:149
#, python-format
msgid "processing %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:153
#, python-format
msgid "polling final stats for %r"
msgstr ""

#: ceilometer/compute/notifications/cpu.py:55
#, python-format
msgid "An error occurred while building %(m)s sample: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:35
#, python-format
msgid "checking instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:39
#, python-format
msgid "CPUTIME USAGE: %(instance)s %(time)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:53
#: ceilometer/compute/pollsters/cpu.py:85
#: ceilometer/compute/pollsters/disk.py:97
#: ceilometer/compute/pollsters/disk.py:205
#: ceilometer/compute/pollsters/memory.py:47
#: ceilometer/compute/pollsters/net.py:104
#, python-format
msgid "Exception while getting samples %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:56
#, python-format
msgid "Obtaining CPU time is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:59
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:69
#, python-format
msgid "Checking CPU util for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:73
#, python-format
msgid "CPU UTIL: %(instance)s %(util)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:88
#, python-format
msgid "Obtaining CPU Util is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:91
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:100
#: ceilometer/compute/pollsters/disk.py:208
#: ceilometer/compute/pollsters/net.py:107
#, python-format
msgid "%(inspector)s does not provide data for  %(pollster)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:105
#: ceilometer/compute/pollsters/disk.py:214
#: ceilometer/compute/pollsters/net.py:112
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:31
#, python-format
msgid "Checking memory usage for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:35
#, python-format
msgid "MEMORY USAGE: %(instance)s %(usage)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:50
#, python-format
msgid "Obtaining Memory Usage is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:53
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/net.py:90
#, python-format
msgid "checking net info for instance %s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:231
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:182
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:184
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:64
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:77
msgid "Connection to libvirt broke"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:117
#, python-format
msgid ""
"Failed to inspect vnics of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:153
#, python-format
msgid ""
"Failed to inspect disks of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:86
#: ceilometer/compute/virt/vmware/inspector.py:103
#: ceilometer/compute/virt/vmware/inspector.py:135
#: ceilometer/compute/virt/vmware/inspector.py:148
#, python-format
msgid "VM %s not found in VMware Vsphere"
msgstr ""

#: ceilometer/dispatcher/database.py:50
#, python-format
msgid ""
"metering data %(counter_name)s for %(resource_id)s @ %(timestamp)s: "
"%(counter_volume)s"
msgstr ""

#: ceilometer/dispatcher/database.py:69
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/database.py:72
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/energy/kwapi.py:77
msgid "Kwapi endpoint not found"
msgstr ""

#: ceilometer/event/converter.py:77
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr ""

#: ceilometer/event/converter.py:86
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:96
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr ""

#: ceilometer/event/converter.py:111
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:117
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:169
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:342
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/event/converter.py:366
#, python-format
msgid "Event Definitions configuration file: %s"
msgstr ""

#: ceilometer/event/converter.py:376
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr ""

#: ceilometer/event/converter.py:382
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr ""

#: ceilometer/event/converter.py:389
msgid "No Event Definitions configuration file found! Using default config."
msgstr ""

#: ceilometer/event/converter.py:393
#, python-format
msgid "Event Definitions: %s"
msgstr ""

#: ceilometer/hardware/plugin.py:71
#, python-format
msgid "inspector call %(func)r failed for host %(host)s: %(err)s"
msgstr ""

#: ceilometer/hardware/plugin.py:103
#, python-format
msgid "Can NOT load inspector %(name)s: %(err)s"
msgstr ""

#: ceilometer/network/floatingip.py:45
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr ""

#: ceilometer/network/notifications.py:79
#, python-format
msgid "network notification %r"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/network/statistics/opendaylight/test_client.py:144
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:166
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/swift.py:70
msgid "Swift endpoint not found"
msgstr ""

#: ceilometer/openstack/common/eventlet_backdoor.py:140
#, python-format
msgid "Eventlet backdoor listening on %(port)s for process %(pid)d"
msgstr ""

#: ceilometer/openstack/common/excutils.py:62
#, python-format
msgid "Original exception being dropped: %s"
msgstr ""

#: ceilometer/openstack/common/excutils.py:91
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr ""

#: ceilometer/openstack/common/fileutils.py:62
#, python-format
msgid "Reloading cached file %s"
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:263
msgid "Message objects do not support addition."
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:272
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: ceilometer/openstack/common/lockutils.py:82
#, python-format
msgid "Created lock path: %s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:93
#, python-format
msgid "Got file lock \"%s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:117
#, python-format
msgid "Released file lock \"%s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:119
#, python-format
msgid "Could not release the acquired lock `%s`"
msgstr ""

#: ceilometer/openstack/common/lockutils.py:161
#, python-format
msgid "Attempting to grab external lock \"%(lock)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:187
#, python-format
msgid "Got semaphore \"%(lock)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:244
#, python-format
msgid "Got semaphore / lock \"%(function)s\""
msgstr ""

#: ceilometer/openstack/common/lockutils.py:248
#, python-format
msgid "Semaphore / lock released \"%(function)s\""
msgstr ""

#: ceilometer/openstack/common/log.py:313
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:416
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ceilometer/openstack/common/log.py:467
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:688
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:82
#, python-format
msgid "task run outlasted interval by %s sec"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:89
msgid "in fixed duration looping call"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:129
#, python-format
msgid "Dynamic looping call sleeping for %.02f seconds"
msgstr ""

#: ceilometer/openstack/common/loopingcall.py:136
msgid "in dynamic looping call"
msgstr ""

#: ceilometer/openstack/common/policy.py:74
msgid "JSON file containing policy"
msgstr ""

#: ceilometer/openstack/common/policy.py:77
msgid "Rule enforced when requested rule is not found"
msgstr ""

#: ceilometer/openstack/common/policy.py:91
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: ceilometer/openstack/common/policy.py:181
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: ceilometer/openstack/common/policy.py:211
msgid "Rules successfully reloaded"
msgstr ""

#: ceilometer/openstack/common/policy.py:257
#, python-format
msgid "Rule %s will be now enforced"
msgstr ""

#: ceilometer/openstack/common/policy.py:272
#, python-format
msgid "Rule [%s] doesn't exist"
msgstr ""

#: ceilometer/openstack/common/policy.py:480
#, python-format
msgid "Failed to understand rule %s"
msgstr ""

#: ceilometer/openstack/common/policy.py:490
#, python-format
msgid "No handler for matches of kind %s"
msgstr ""

#: ceilometer/openstack/common/policy.py:760
#, python-format
msgid "Failed to understand rule %r"
msgstr ""

#: ceilometer/openstack/common/service.py:166
#: ceilometer/openstack/common/service.py:384
msgid "Full set of CONF:"
msgstr ""

#: ceilometer/openstack/common/service.py:175
#: ceilometer/openstack/common/service.py:269
#, python-format
msgid "Caught %s, exiting"
msgstr ""

#: ceilometer/openstack/common/service.py:187
msgid "Exception during rpc cleanup."
msgstr ""

#: ceilometer/openstack/common/service.py:238
msgid "Parent process has died unexpectedly, exiting"
msgstr ""

#: ceilometer/openstack/common/service.py:275
msgid "Unhandled exception"
msgstr ""

#: ceilometer/openstack/common/service.py:308
msgid "Forking too fast, sleeping"
msgstr ""

#: ceilometer/openstack/common/service.py:327
#, python-format
msgid "Started child %d"
msgstr ""

#: ceilometer/openstack/common/service.py:337
#, python-format
msgid "Starting %d workers"
msgstr ""

#: ceilometer/openstack/common/service.py:354
#, python-format
msgid "Child %(pid)d killed by signal %(sig)d"
msgstr ""

#: ceilometer/openstack/common/service.py:358
#, python-format
msgid "Child %(pid)s exited with status %(code)d"
msgstr ""

#: ceilometer/openstack/common/service.py:362
#, python-format
msgid "pid %d not in child list"
msgstr ""

#: ceilometer/openstack/common/service.py:392
#, python-format
msgid "Caught %s, stopping children"
msgstr ""

#: ceilometer/openstack/common/service.py:410
#, python-format
msgid "Waiting on %d children to exit"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:50
#, python-format
msgid "Unable to find cert_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:53
#, python-format
msgid "Unable to find ca_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:56
#, python-format
msgid "Unable to find key_file : %s"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:59
msgid ""
"When running server in SSL mode, you must specify both a cert_file and "
"key_file option value in your configuration file"
msgstr ""

#: ceilometer/openstack/common/sslutils.py:98
#, python-format
msgid "Invalid SSL version : %s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:86
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:188
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:195
#, python-format
msgid "Unknown byte multiplier: %s"
msgstr ""

#: ceilometer/openstack/common/versionutils.py:69
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""

#: ceilometer/openstack/common/versionutils.py:73
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""

#: ceilometer/openstack/common/db/exception.py:42
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:191
msgid "version should be an integer"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:214
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:238
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:596
msgid "DB exception wrapped."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:665
#, python-format
msgid "Database server has gone away: %s"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:745
msgid ""
"This application has not enabled MySQL traditional mode, which means "
"silent data corruption may occur. Please encourage the application "
"developers to enable this mode."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/session.py:770
#, python-format
msgid "SQL connection failed. %s attempts left."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:63
#, python-format
msgid "Got lock \"%s\""
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/test_migrations.py:66
#, python-format
msgid "Lock released \"%s\""
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:57
msgid "Sort key supplied was not valid."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:96
msgid "Id not in sort_keys; is sort_keys unique?"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:118
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:193
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:199
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:279
#, python-format
msgid "Deleting duplicated row with id: %(id)s from table: %(table)s"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:300
msgid "Unsupported id columns type"
msgstr ""

#: ceilometer/openstack/common/middleware/catch_errors.py:40
#, python-format
msgid "An error occurred during processing the request: %s"
msgstr ""

#: ceilometer/openstack/common/middleware/notifier.py:40
#, python-format
msgid "An exception occurred processing the API call: %s "
msgstr ""

#: ceilometer/openstack/common/middleware/sizelimit.py:55
#: ceilometer/openstack/common/middleware/sizelimit.py:64
#: ceilometer/openstack/common/middleware/sizelimit.py:75
msgid "Request is too large."
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:129
#, python-format
msgid "%s not in valid priorities"
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:145
#, python-format
msgid ""
"Problem '%(e)s' attempting to send to notification system. "
"Payload=%(payload)s"
msgstr ""

#: ceilometer/openstack/common/notifier/api.py:164
#, python-format
msgid "Failed to load notifier %s. These notifications will not be sent."
msgstr ""

#: ceilometer/openstack/common/notifier/rpc_notifier.py:45
#: ceilometer/openstack/common/notifier/rpc_notifier2.py:51
#, python-format
msgid "Could not send notification to %(topic)s. Payload=%(message)s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:75
msgid "Pool creating new connection"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:202
#, python-format
msgid "No calling threads waiting for msg_id : %(msg_id)s, message : %(data)s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:205
#, python-format
msgid "_call_waiters: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:212
#, python-format
msgid ""
"Number of call waiters is greater than warning threshold: %d. There could"
" be a MulticallProxyWaiter leak."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:290
#, python-format
msgid "unpacked context: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:342
#, python-format
msgid "UNIQUE_ID is %s."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:435
#, python-format
msgid "received %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:443
#, python-format
msgid "no method for message: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:444
#, python-format
msgid "No method for message: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:472
#: ceilometer/openstack/common/rpc/impl_zmq.py:280
#, python-format
msgid "Expected exception during message handling (%s)"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:480
#: ceilometer/openstack/common/rpc/impl_zmq.py:286
msgid "Exception during message handling"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:554
#, python-format
msgid "Making synchronous call on %s ..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:557
#, python-format
msgid "MSG_ID is %s"
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:583
#, python-format
msgid "Making asynchronous cast on %s..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:592
msgid "Making asynchronous fanout cast..."
msgstr ""

#: ceilometer/openstack/common/rpc/amqp.py:620
#, python-format
msgid "Sending %(event_type)s on %(topic)s"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:76
msgid "An unknown RPC related exception occurred."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:88
msgid "Exception in string format operation"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:106
#, python-format
msgid ""
"Remote error: %(exc_type)s %(value)s\n"
"%(traceback)s."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:123
#, python-format
msgid ""
"Timeout while waiting on RPC response - topic: \"%(topic)s\", RPC method:"
" \"%(method)s\" info: \"%(info)s\""
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:140
#: ceilometer/openstack/common/rpc/common.py:141
#: ceilometer/openstack/common/rpc/common.py:142
msgid "<unknown>"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:146
#, python-format
msgid "Found duplicate message(%(msg_id)s). Skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:150
msgid "Invalid reuse of an RPC connection."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:154
#, python-format
msgid "Specified RPC version, %(version)s, not supported by this endpoint."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:159
#, python-format
msgid ""
"Specified RPC envelope version, %(version)s, not supported by this "
"endpoint."
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:164
#, python-format
msgid "Specified RPC version cap, %(version_cap)s, is too low"
msgstr ""

#: ceilometer/openstack/common/rpc/common.py:292
#, python-format
msgid "Returning exception %s to caller"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:156
msgid "Failed to process message ... skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:160
msgid "Failed to process message ... will requeue."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:495
#, python-format
msgid "Reconnecting to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:517
#, python-format
msgid "Connected to AMQP server on %(hostname)s:%(port)d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:554
#, python-format
msgid ""
"Unable to connect to AMQP server on %(hostname)s:%(port)d after "
"%(max_retries)d tries: %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:568
#, python-format
msgid ""
"AMQP server on %(hostname)s:%(port)d is unreachable: %(err_str)s. Trying "
"again in %(sleep_time)d seconds."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:622
#: ceilometer/openstack/common/rpc/impl_qpid.py:573
#, python-format
msgid "Failed to declare consumer for topic '%(topic)s': %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:640
#: ceilometer/openstack/common/rpc/impl_qpid.py:588
#, python-format
msgid "Timed out waiting for RPC response: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:644
#: ceilometer/openstack/common/rpc/impl_qpid.py:592
#, python-format
msgid "Failed to consume message from queue: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_kombu.py:683
#: ceilometer/openstack/common/rpc/impl_qpid.py:627
#, python-format
msgid "Failed to publish message to topic '%(topic)s': %(err_str)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:87
#, python-format
msgid "Invalid value for qpid_topology_version: %d"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:191
msgid "Failed to process message... skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:515
#, python-format
msgid "Unable to connect to AMQP server: %(e)s. Sleeping %(delay)s seconds"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:521
#, python-format
msgid "Connected to AMQP server on %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:534
msgid "Re-established AMQP queues"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_qpid.py:600
msgid "Error processing message.  Skipping it."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:96
msgid "JSON serialization failed."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:101
#, python-format
msgid "Deserializing: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:136
#, python-format
msgid "Connecting to %(addr)s with %(type)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:137
#, python-format
msgid "-> Subscribed to %(subscribe)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:138
#, python-format
msgid "-> bind: %(bind)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:146
msgid "Could not open socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:158
#, python-format
msgid "Subscribing to %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:195
msgid "ZeroMQ socket could not be closed."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:200
msgid "You cannot recv on this socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:205
msgid "You cannot send on this socket."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:267
#, python-format
msgid "Running func with context: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:305
msgid "Sending reply"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:339
msgid "RPC message did not include method."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:371
msgid "Registering reactor"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:383
msgid "In reactor registered"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:388
msgid "Consuming socket"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:438
#, python-format
msgid "Creating proxy for topic: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:444
msgid "Topic contained dangerous characters."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:476
msgid "Topic socket file creation failed."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:482
#, python-format
msgid "Local per-topic backlog buffer full for topic %(topic)s. Dropping message."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:498
#, python-format
msgid "Required IPC directory does not exist at %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:507
#, python-format
msgid "Permission denied to IPC directory at %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:510
msgid "Could not create ZeroMQ receiver daemon. Socket may already be in use."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:544
#, python-format
msgid "CONSUMER RECEIVED DATA: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:563
msgid "ZMQ Envelope version unsupported or unknown."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:591
msgid "Skipping topic registration. Already registered."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:598
#, python-format
msgid "Consumer is a zmq.%s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:650
msgid "Creating payload"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:663
msgid "Creating queue socket for reply waiter"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:676
msgid "Sending cast"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:679
msgid "Cast sent; Waiting reply"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:682
#, python-format
msgid "Received message: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:683
msgid "Unpacking response"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:692
msgid "Unsupported or unknown ZMQ envelope returned."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:699
msgid "RPC Message Invalid."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:722
#, python-format
msgid "%(msg)s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:725
#, python-format
msgid "Sending message(s) to: %s"
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:729
msgid "No matchmaker results. Not casting."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:732
msgid "No match from matchmaker."
msgstr ""

#: ceilometer/openstack/common/rpc/impl_zmq.py:814
#, python-format
msgid "rpc_zmq_matchmaker = %(orig)s is deprecated; use %(new)s instead"
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:46
msgid "Match not found by MatchMaker."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:80
msgid "Matchmaker does not implement registration or heartbeat."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:216
#, python-format
msgid "Matchmaker unregistered: %(key)s, %(host)s"
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker.py:228
msgid "Register before starting heartbeat."
msgstr ""

#: ceilometer/openstack/common/rpc/matchmaker_ring.py:76
#: ceilometer/openstack/common/rpc/matchmaker_ring.py:94
#, python-format
msgid "No key defining hosts for topic '%s', see ringfile"
msgstr ""

#: ceilometer/openstack/common/rpc/service.py:47
#, python-format
msgid "Creating Consumer connection for Service %s"
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/rpc.py:106
#, python-format
msgid "Publishing policy set to %s, override backend retry config to 1"
msgstr ""

#: ceilometer/publisher/rpc.py:111
#, python-format
msgid "Publishing policy set to %s"
msgstr ""

#: ceilometer/publisher/rpc.py:113
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/rpc.py:138
#, python-format
msgid "Publishing %(m)d samples on %(t)s"
msgstr ""

#: ceilometer/publisher/rpc.py:152
#, python-format
msgid "Publishing %(m)d samples on %(n)s"
msgstr ""

#: ceilometer/publisher/rpc.py:177
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/rpc.py:203
#, python-format
msgid "Failed to publish %d samples, queue them"
msgstr ""

#: ceilometer/publisher/rpc.py:207
#, python-format
msgid "Failed to publish %d samples, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:60
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr ""

#: ceilometer/publisher/udp.py:67
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/__init__.py:76
#, python-format
msgid "looking for %(name)r driver in %(namespace)r"
msgstr ""

#: ceilometer/storage/impl_hbase.py:136
msgid "Creating a new in-memory HBase Connection object"
msgstr ""

#: ceilometer/storage/impl_hbase.py:156
msgid "Dropping HBase schema..."
msgstr ""

#: ceilometer/storage/impl_hbase.py:168
msgid "Cannot disable table but ignoring error"
msgstr ""

#: ceilometer/storage/impl_hbase.py:172
msgid "Cannot delete table but ignoring error"
msgstr ""

#: ceilometer/storage/impl_hbase.py:183
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:348 ceilometer/storage/impl_hbase.py:361
#, python-format
msgid "source: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:397
#, python-format
msgid "Query Meter table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:440
msgid "Pagination not implemented"
msgstr ""

#: ceilometer/storage/impl_hbase.py:446
#, python-format
msgid "Query Resource table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:478
#, python-format
msgid "Query Meter Table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:715
msgid "Opening in-memory HBase connection"
msgstr ""

#: ceilometer/storage/impl_log.py:57
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr ""

#: ceilometer/storage/impl_log.py:70
#, python-format
msgid "Dropping data with TTL %d"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:357
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:1055
#, python-format
msgid "Failed to record event: %s"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:1070
#, python-format
msgid "Getting events that match filter: %s"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:1187
#, python-format
msgid "Get traits for %s"
msgstr ""

#: ceilometer/storage/pymongo_base.py:121
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: ceilometer/transformer/conversions.py:69
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr ""

#: ceilometer/transformer/conversions.py:116
#: ceilometer/transformer/conversions.py:139
#, python-format
msgid "handling sample %s"
msgstr ""

#: ceilometer/transformer/conversions.py:119
#: ceilometer/transformer/conversions.py:160
#, python-format
msgid "converted to: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:162
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

