# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 2014.2.dev56.g0da00bf\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-06-20 06:01+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/agent.py:83
#, python-format
msgid "Polling pollster %s"
msgstr ""

#: ceilometer/agent.py:93
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent.py:169
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent.py:171
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/cli.py:117
msgid "Clearing expired metering data"
msgstr ""

#: ceilometer/cli.py:122
msgid "Nothing to clean, database time to live is disabled"
msgstr ""

#: ceilometer/collector.py:84
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:87
#, python-format
msgid "UDP: Storing %s"
msgstr ""

#: ceilometer/collector.py:91
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/notification.py:80 ceilometer/notifier.py:48
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/notification.py:92
#, python-format
msgid "Event types from %(name)s: %(type)s (ack_on_error=%(error)s)"
msgstr ""

#: ceilometer/notifier.py:39
#, python-format
msgid "loading notification handlers from %s"
msgstr ""

#: ceilometer/pipeline.py:237
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:256
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr ""

#: ceilometer/pipeline.py:269
#, python-format
msgid "Pipeline %(pipeline)s: Sample dropped by transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:276
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:296
#, python-format
msgid "Pipeline %(pipeline)s: Transform sample %(smp)s from %(trans)s transformer"
msgstr ""

#: ceilometer/pipeline.py:310
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:329
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:490
msgid "detected decoupled pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:500
msgid "detected deprecated pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:520
#, python-format
msgid "Pipeline config file: %s"
msgstr ""

#: ceilometer/pipeline.py:526
#, python-format
msgid "Pipeline config: %s"
msgstr ""

#: ceilometer/plugin.py:65
msgid ""
"get_exchange_topics API of NotificationPlugin isdeprecated, implements "
"get_targets instead."
msgstr ""

#: ceilometer/service.py:103
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: ceilometer/alarm/rpc.py:53
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: ceilometer/alarm/service.py:90
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:95
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:100
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: ceilometer/alarm/service.py:104
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:219
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:228
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:234
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr ""

#: ceilometer/alarm/service.py:239
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:258
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:70
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:82
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:50
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:73
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:77
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:99
#: ceilometer/alarm/evaluator/threshold.py:176
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:62
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:73
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:82
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:91
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:96
#, python-format
msgid "stats query %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:102
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:111
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:135
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:139
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:195
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: ceilometer/alarm/notifier/log.py:31 ceilometer/alarm/notifier/rest.py:58
#, python-format
msgid ""
"Notifying alarm %(alarm_id)s from %(previous)s to %(current)s with action"
" %(action)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:131
#, python-format
msgid "triggering %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:132
#, python-format
msgid "known evaluators %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:135
#, python-format
msgid "per evaluator allocation %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:145
#, python-format
msgid ""
"%(this)s bailing on distribution cycle as older partition detected: "
"%(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:151
#, python-format
msgid "%(verb)s-ing %(alloc)s to %(eval)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:155
#, python-format
msgid "master taking %s for self"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:173
#, python-format
msgid "newly deleted alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:176
msgid "alarm deletion activity requires rebalance"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:201
#, python-format
msgid "%s still warming up"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:206
#, python-format
msgid "last heard from %(report)s %(delta)s seconds ago"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:211
#, python-format
msgid "%(this)s detects stale evaluator: %(stale)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:216
#, python-format
msgid "%(this)s sees older potential master: %(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:218
#, python-format
msgid "%(this)s is master?: %(is_master)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:231
#, python-format
msgid "newly created alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:242
#, python-format
msgid "%(this)s not overtaken as master? %(still_ahead)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:252
#, python-format
msgid "%s checking mastership status"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:259
msgid "mastership check failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:269
#, python-format
msgid "%(this)s knows about %(reports)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:275
#, python-format
msgid "%(this)s got assignment: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:282
#, python-format
msgid "%(this)s got allocation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:288
#, python-format
msgid "%s reporting presence"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:292
msgid "presence reporting failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:297
#, python-format
msgid "%s has no assigned alarms to evaluate"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:301
#, python-format
msgid "%(this)s alarms for evaluation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:307
msgid "assignment retrieval failed"
msgstr ""

#: ceilometer/api/app.py:162
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: ceilometer/api/app.py:163
msgid "Configuration:"
msgstr ""

#: ceilometer/api/app.py:167
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: ceilometer/api/app.py:171
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: ceilometer/api/middleware.py:111
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:86
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2.py:257
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:262
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:267
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:278
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:752
msgid "clamping min timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:757
msgid "clamping max timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:834 ceilometer/api/controllers/v2.py:1099
msgid "Limit must be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:917
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2.py:929
#, python-format
msgid "computed value coming from %r"
msgstr ""

#: ceilometer/api/controllers/v2.py:1115
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2.py:1299
msgid "Limit should be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:1391
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2.py:1392
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1479
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2.py:1554
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/api/controllers/v2.py:1595
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1604
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr ""

#: ceilometer/api/controllers/v2.py:1655
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: ceilometer/api/controllers/v2.py:1776 ceilometer/api/controllers/v2.py:1892
msgid "Alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1780
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: ceilometer/api/controllers/v2.py:1790
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1794
msgid "threshold_rule and combination_rule cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2.py:1961
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:1968
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr ""

#: ceilometer/api/controllers/v2.py:1976
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1977 ceilometer/api/controllers/v2.py:2127
msgid "Alarm incorrect"
msgstr ""

#: ceilometer/api/controllers/v2.py:2029
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2.py:2120
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:2126
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2278
#, python-format
msgid "operator %s not supported"
msgstr ""

#: ceilometer/api/controllers/v2.py:2299
#, python-format
msgid "Getting traits for %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2364
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2.py:2367
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/central/plugin.py:39
#, python-format
msgid "Skip due to keystone error %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:81
#, python-format
msgid "using provided stats gatherer %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:84
msgid "making a new stats gatherer"
msgstr ""

#: ceilometer/compute/nova_notifier.py:113
#, python-format
msgid "INFO %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:146
#, python-format
msgid "ignoring %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:148
#, python-format
msgid "processing %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:152
#, python-format
msgid "polling final stats for %r"
msgstr ""

#: ceilometer/compute/notifications/cpu.py:54
#, python-format
msgid "An error occurred while building %(m)s sample: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:34
#, python-format
msgid "checking instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:38
#, python-format
msgid "CPUTIME USAGE: %(instance)s %(time)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:52
#: ceilometer/compute/pollsters/cpu.py:83
#: ceilometer/compute/pollsters/disk.py:96
#: ceilometer/compute/pollsters/disk.py:203
#: ceilometer/compute/pollsters/memory.py:47
#: ceilometer/compute/pollsters/net.py:105
#, python-format
msgid "Exception while getting samples %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:55
#, python-format
msgid "Obtaining CPU time is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:58
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:67
#, python-format
msgid "Checking CPU util for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:71
#, python-format
msgid "CPU UTIL: %(instance)s %(util)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:86
#, python-format
msgid "Obtaining CPU Util is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:89
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:99
#: ceilometer/compute/pollsters/disk.py:206
#: ceilometer/compute/pollsters/net.py:108
#, python-format
msgid "%(inspector)s does not provide data for  %(pollster)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:104
#: ceilometer/compute/pollsters/disk.py:212
#: ceilometer/compute/pollsters/net.py:113
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:31
#, python-format
msgid "Checking memory usage for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:35
#, python-format
msgid "MEMORY USAGE: %(instance)s %(usage)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:50
#, python-format
msgid "Obtaining Memory Usage is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:53
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/net.py:91
#, python-format
msgid "checking net info for instance %s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:230
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:182
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:184
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:64
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:77
msgid "Connection to libvirt broke"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:117
#, python-format
msgid ""
"Failed to inspect vnics of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:152
#, python-format
msgid ""
"Failed to inspect disks of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:86
#: ceilometer/compute/virt/vmware/inspector.py:103
#: ceilometer/compute/virt/vmware/inspector.py:135
#: ceilometer/compute/virt/vmware/inspector.py:148
#, python-format
msgid "VM %s not found in VMware Vsphere"
msgstr ""

#: ceilometer/dispatcher/__init__.py:43
#, python-format
msgid "loading dispatchers from %s"
msgstr ""

#: ceilometer/dispatcher/__init__.py:51
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr ""

#: ceilometer/dispatcher/database.py:49
#, python-format
msgid ""
"metering data %(counter_name)s for %(resource_id)s @ %(timestamp)s: "
"%(counter_volume)s"
msgstr ""

#: ceilometer/dispatcher/database.py:68
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/database.py:71
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/energy/kwapi.py:77
msgid "Kwapi endpoint not found"
msgstr ""

#: ceilometer/event/converter.py:76
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr ""

#: ceilometer/event/converter.py:85
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:95
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr ""

#: ceilometer/event/converter.py:110
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:116
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:168
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:344
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/event/converter.py:368
#, python-format
msgid "Event Definitions configuration file: %s"
msgstr ""

#: ceilometer/event/converter.py:378
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr ""

#: ceilometer/event/converter.py:384
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr ""

#: ceilometer/event/converter.py:391
msgid "No Event Definitions configuration file found! Using default config."
msgstr ""

#: ceilometer/event/converter.py:395
#, python-format
msgid "Event Definitions: %s"
msgstr ""

#: ceilometer/event/endpoint.py:37
msgid "Loading event definitions"
msgstr ""

#: ceilometer/event/endpoint.py:63
#, python-format
msgid "Saving event \"%s\""
msgstr ""

#: ceilometer/event/endpoint.py:70
msgid "Event is not implemented with the storage backend"
msgstr ""

#: ceilometer/hardware/plugin.py:71
#, python-format
msgid "inspector call %(func)r failed for host %(host)s: %(err)s"
msgstr ""

#: ceilometer/hardware/plugin.py:103
#, python-format
msgid "Can NOT load inspector %(name)s: %(err)s"
msgstr ""

#: ceilometer/network/floatingip.py:44
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr ""

#: ceilometer/network/notifications.py:76
#, python-format
msgid "network notification %r"
msgstr ""

#: ceilometer/network/services/lbaas.py:268
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:58
#: ceilometer/network/statistics/opencontrail/client.py:88
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/network/statistics/opendaylight/test_client.py:144
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:169
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/swift.py:69
msgid "Swift endpoint not found"
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:320
msgid "Message objects do not support addition."
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:330
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: ceilometer/openstack/common/lockutils.py:102
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: ceilometer/openstack/common/log.py:327
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:436
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ceilometer/openstack/common/log.py:487
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:725
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: ceilometer/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: ceilometer/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: ceilometer/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: ceilometer/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: ceilometer/openstack/common/strutils.py:92
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:197
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: ceilometer/openstack/common/strutils.py:206
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ceilometer/openstack/common/db/exception.py:44
msgid "Invalid Parameter: Unicode is not supported by the current database."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:190
msgid "version should be an integer"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:226
#, python-format
msgid ""
"Tables \"%s\" have non utf8 collation, please make sure all tables are "
"CHARSET=utf8"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/migration.py:250
msgid ""
"The database is not under version control, but has tables. Please stamp "
"the current version of the schema manually."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:58
msgid "Sort key supplied was not valid."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:119
msgid "Unknown sort direction, must be 'desc' or 'asc'"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:162
#, python-format
msgid ""
"There is no `deleted` column in `%s` table. Project doesn't use soft-"
"deleted feature."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:174
#, python-format
msgid "Unrecognized read_deleted value '%s'"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:181
#, python-format
msgid "There is no `project_id` column in `%s` table."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:243
msgid "model should be a subclass of ModelBase"
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:294
#, python-format
msgid ""
"Please specify column %s in col_name_col_instance param. It is required "
"because column has unsupported type by sqlite)."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:300
#, python-format
msgid ""
"col_name_col_instance param has wrong type of column instance for column "
"%s It should be instance of sqlalchemy.Column."
msgstr ""

#: ceilometer/openstack/common/db/sqlalchemy/utils.py:408
msgid "Unsupported id columns type"
msgstr ""

#: ceilometer/openstack/common/middleware/sizelimit.py:55
#: ceilometer/openstack/common/middleware/sizelimit.py:64
#: ceilometer/openstack/common/middleware/sizelimit.py:76
msgid "Request is too large."
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/rpc.py:99
#, python-format
msgid "Publishing policy set to %s, override backend retry config to 1"
msgstr ""

#: ceilometer/publisher/rpc.py:103
#, python-format
msgid "Publishing policy set to %s"
msgstr ""

#: ceilometer/publisher/rpc.py:105
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/rpc.py:161
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/rpc.py:183
#, python-format
msgid "Failed to publish %d samples, queue them"
msgstr ""

#: ceilometer/publisher/rpc.py:187
#, python-format
msgid "Failed to publish %d samples, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:59
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr ""

#: ceilometer/publisher/udp.py:66
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/__init__.py:78
#, python-format
msgid "looking for %(name)r driver in %(namespace)r"
msgstr ""

#: ceilometer/storage/impl_hbase.py:173
msgid "Creating a new in-memory HBase Connection object"
msgstr ""

#: ceilometer/storage/impl_hbase.py:190
msgid "Dropping HBase schema..."
msgstr ""

#: ceilometer/storage/impl_hbase.py:200
msgid "Cannot disable table but ignoring error"
msgstr ""

#: ceilometer/storage/impl_hbase.py:204
msgid "Cannot delete table but ignoring error"
msgstr ""

#: ceilometer/storage/impl_hbase.py:215
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:389 ceilometer/storage/impl_hbase.py:438
#, python-format
msgid "Query Resource table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:431
msgid "Pagination not implemented"
msgstr ""

#: ceilometer/storage/impl_hbase.py:479
#, python-format
msgid "Query Meter Table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:628
#: ceilometer/storage/impl_sqlalchemy.py:951
#, python-format
msgid "Failed to record event: %s"
msgstr ""

#: ceilometer/storage/impl_log.py:43
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr ""

#: ceilometer/storage/impl_log.py:56
#, python-format
msgid "Dropping data with TTL %d"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:299
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:966
#, python-format
msgid "Getting events that match filter: %s"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:1083
#, python-format
msgid "Get traits for %s"
msgstr ""

#: ceilometer/storage/hbase/inmemory.py:250
msgid "Opening in-memory HBase connection"
msgstr ""

#: ceilometer/storage/mongo/utils.py:127
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: ceilometer/storage/mongo/utils.py:142
#: ceilometer/tests/storage/test_pymongo_base.py:206
#, python-format
msgid "Unable to connect to the database after %(retries)d retries. Giving up."
msgstr ""

#: ceilometer/storage/mongo/utils.py:146
#: ceilometer/tests/storage/test_pymongo_base.py:201
#, python-format
msgid ""
"Unable to connect to the database server: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

#: ceilometer/transformer/conversions.py:70
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr ""

#: ceilometer/transformer/conversions.py:117
#: ceilometer/transformer/conversions.py:140
#, python-format
msgid "handling sample %s"
msgstr ""

#: ceilometer/transformer/conversions.py:120
#: ceilometer/transformer/conversions.py:161
#, python-format
msgid "converted to: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:163
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

