# Translations template for ceilometer.
# Copyright (C) 2014 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 2014.2.dev9.g2adf348\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2014-10-07 16:24+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/agent.py:108
#, python-format
msgid "Polling pollster %(poll)s in the context of %(src)s"
msgstr ""

#: ceilometer/agent.py:127
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent.py:241
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent.py:243
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/collector.py:103
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:106
#, python-format
msgid "UDP: Storing %s"
msgstr ""

#: ceilometer/collector.py:110
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/notification.py:80 ceilometer/notifier.py:48
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/notification.py:92
#, python-format
msgid "Event types from %(name)s: %(type)s (ack_on_error=%(error)s)"
msgstr ""

#: ceilometer/notifier.py:39
#, python-format
msgid "loading notification handlers from %s"
msgstr ""

#: ceilometer/pipeline.py:233
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:252
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr ""

#: ceilometer/pipeline.py:265
#, python-format
msgid "Pipeline %(pipeline)s: Sample dropped by transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:272
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:292
#, python-format
msgid "Pipeline %(pipeline)s: Transform sample %(smp)s from %(trans)s transformer"
msgstr ""

#: ceilometer/pipeline.py:306
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:325
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:485
msgid "detected decoupled pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:495
msgid "detected deprecated pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:515
#, python-format
msgid "Pipeline config file: %s"
msgstr ""

#: ceilometer/pipeline.py:521
#, python-format
msgid "Pipeline config: %s"
msgstr ""

#: ceilometer/plugin.py:66
msgid ""
"get_exchange_topics API of NotificationPlugin isdeprecated, implements "
"get_targets instead."
msgstr ""

#: ceilometer/service.py:104
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: ceilometer/alarm/rpc.py:56
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: ceilometer/alarm/service.py:93
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:98
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:103
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: ceilometer/alarm/service.py:107
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:260
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:269
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:275
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr ""

#: ceilometer/alarm/service.py:280
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:299
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:73
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:85
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:52
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:74
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:78
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:99
#: ceilometer/alarm/evaluator/threshold.py:177
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:63
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:73
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:82
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:91
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:96
#, python-format
msgid "stats query %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:102
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:113
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:136
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:140
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:196
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: ceilometer/alarm/notifier/log.py:31
#, python-format
msgid ""
"Notifying alarm %(alarm_id)s from %(previous)s to %(current)s with action"
" %(action)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/notifier/rest.py:66
#, python-format
msgid ""
"Notifying alarm %(alarm_id)s from %(previous)s to %(current)s with action"
" %(action)s because %(reason)s. request-id: %(request_id)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:132
#, python-format
msgid "triggering %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:133
#, python-format
msgid "known evaluators %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:136
#, python-format
msgid "per evaluator allocation %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:146
#, python-format
msgid ""
"%(this)s bailing on distribution cycle as older partition detected: "
"%(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:152
#, python-format
msgid "%(verb)s-ing %(alloc)s to %(eval)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:156
#, python-format
msgid "master taking %s for self"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:174
#, python-format
msgid "newly deleted alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:177
msgid "alarm deletion activity requires rebalance"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:202
#, python-format
msgid "%s still warming up"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:207
#, python-format
msgid "last heard from %(report)s %(delta)s seconds ago"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:212
#, python-format
msgid "%(this)s detects stale evaluator: %(stale)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:217
#, python-format
msgid "%(this)s sees older potential master: %(older)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:219
#, python-format
msgid "%(this)s is master?: %(is_master)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:232
#, python-format
msgid "newly created alarms %s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:243
#, python-format
msgid "%(this)s not overtaken as master? %(still_ahead)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:253
#, python-format
msgid "%s checking mastership status"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:260
msgid "mastership check failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:270
#, python-format
msgid "%(this)s knows about %(reports)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:276
#, python-format
msgid "%(this)s got assignment: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:283
#, python-format
msgid "%(this)s got allocation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:289
#, python-format
msgid "%s reporting presence"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:293
msgid "presence reporting failed"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:298
#, python-format
msgid "%s has no assigned alarms to evaluate"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:302
#, python-format
msgid "%(this)s alarms for evaluation: %(alarms)s"
msgstr ""

#: ceilometer/alarm/partition/coordination.py:308
msgid "assignment retrieval failed"
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:92
#: ceilometer/storage/impl_hbase.py:155
msgid "Creating a new in-memory HBase Connection object"
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:107
#: ceilometer/storage/impl_hbase.py:170
msgid "Dropping HBase schema..."
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:114
#: ceilometer/storage/impl_hbase.py:178
msgid "Cannot disable table but ignoring error"
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:118
#: ceilometer/storage/impl_hbase.py:182
msgid "Cannot delete table but ignoring error"
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:129
#: ceilometer/storage/impl_hbase.py:193
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr ""

#: ceilometer/api/app.py:165
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: ceilometer/api/app.py:166
msgid "Configuration:"
msgstr ""

#: ceilometer/api/app.py:170
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: ceilometer/api/app.py:174
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: ceilometer/api/middleware.py:108
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:97
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2.py:105
#, python-format
msgid "Alarm %s not found"
msgstr ""

#: ceilometer/api/controllers/v2.py:107
#, python-format
msgid "Alarm %(alarm_id)s not found in project %(project)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:120
#, python-format
msgid "Alarm quota exceeded for user %(u)s on project %(p)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:313
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:318
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:323
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2.py:334
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2.py:809
msgid "clamping min timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:814
msgid "clamping max timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2.py:890 ceilometer/api/controllers/v2.py:1156
msgid "Limit must be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:973
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2.py:985
#, python-format
msgid "computed value coming from %r"
msgstr ""

#: ceilometer/api/controllers/v2.py:1172
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2.py:1337
#, python-format
msgid "Filter expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1352
#, python-format
msgid "Order-by expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1363
msgid "Limit should be positive"
msgstr ""

#: ceilometer/api/controllers/v2.py:1456
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2.py:1457
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1543
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2.py:1618
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/api/controllers/v2.py:1658
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1667
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr ""

#: ceilometer/api/controllers/v2.py:1718
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: ceilometer/api/controllers/v2.py:1844
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: ceilometer/api/controllers/v2.py:1854
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: ceilometer/api/controllers/v2.py:1858
msgid "threshold_rule and combination_rule cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2.py:1875
#, python-format
msgid "Unable to parse action %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:1878
#, python-format
msgid "Unsupported action %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2041
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:2048
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr ""

#: ceilometer/api/controllers/v2.py:2056
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2057 ceilometer/api/controllers/v2.py:2208
msgid "Alarm incorrect"
msgstr ""

#: ceilometer/api/controllers/v2.py:2108
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2.py:2201
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: ceilometer/api/controllers/v2.py:2207
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2364
msgid "operator {} is incorrect"
msgstr ""

#: ceilometer/api/controllers/v2.py:2386
#, python-format
msgid "Getting traits for %s"
msgstr ""

#: ceilometer/api/controllers/v2.py:2451
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2.py:2454
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/central/plugin.py:66
#, python-format
msgid "Skip due to keystone error %s"
msgstr ""

#: ceilometer/central/plugin.py:73
#, python-format
msgid "Skipping because %s service is not registered in keystone"
msgstr ""

#: ceilometer/cmd/storage.py:39
msgid "Clearing expired metering data"
msgstr ""

#: ceilometer/cmd/storage.py:44
msgid "Nothing to clean, database time to live is disabled"
msgstr ""

#: ceilometer/compute/nova_notifier.py:79
#, python-format
msgid "using provided stats gatherer %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:82
msgid "making a new stats gatherer"
msgstr ""

#: ceilometer/compute/nova_notifier.py:111
#, python-format
msgid "INFO %r"
msgstr ""

#: ceilometer/compute/nova_notifier.py:144
#, python-format
msgid "ignoring %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:146
#, python-format
msgid "processing %s"
msgstr ""

#: ceilometer/compute/nova_notifier.py:150
#, python-format
msgid "polling final stats for %r"
msgstr ""

#: ceilometer/compute/notifications/cpu.py:52
#, python-format
msgid "An error occurred while building %(m)s sample: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:34
#, python-format
msgid "checking instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:38
#, python-format
msgid "CPUTIME USAGE: %(instance)s %(time)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:52
#: ceilometer/compute/pollsters/cpu.py:83
#: ceilometer/compute/pollsters/disk.py:122
#: ceilometer/compute/pollsters/disk.py:327
#: ceilometer/compute/pollsters/memory.py:47
#: ceilometer/compute/pollsters/net.py:107
#, python-format
msgid "Exception while getting samples %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:55
#, python-format
msgid "Obtaining CPU time is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:58
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:67
#, python-format
msgid "Checking CPU util for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:71
#, python-format
msgid "CPU UTIL: %(instance)s %(util)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:86
#, python-format
msgid "Obtaining CPU Util is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:89
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:125
#: ceilometer/compute/pollsters/disk.py:330
#: ceilometer/compute/pollsters/net.py:110
#, python-format
msgid "%(inspector)s does not provide data for  %(pollster)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:130
#: ceilometer/compute/pollsters/disk.py:336
#: ceilometer/compute/pollsters/net.py:115
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:31
#, python-format
msgid "Checking memory usage for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:35
#, python-format
msgid "MEMORY USAGE: %(instance)s %(usage)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:50
#, python-format
msgid "Obtaining Memory Usage is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:53
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/net.py:93
#, python-format
msgid "checking net info for instance %s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:231
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:182
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:184
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:129
#, python-format
msgid ""
"Failed to inspect vnics of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:164
#, python-format
msgid ""
"Failed to inspect disks of %(instance_name)s, domain is in state of "
"SHUTOFF"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:90
#: ceilometer/compute/virt/vmware/inspector.py:107
#: ceilometer/compute/virt/vmware/inspector.py:139
#: ceilometer/compute/virt/vmware/inspector.py:152
#, python-format
msgid "VM %s not found in VMware Vsphere"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:58
msgid "XenAPI not installed"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:64
msgid "Must specify connection_url, and connection_password to use"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:67
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:74
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:106
#, python-format
msgid "VM %s not found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:109
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:130
#, python-format
msgid "Could not get VM %s CPU Utilization"
msgstr ""

#: ceilometer/dispatcher/__init__.py:43
#, python-format
msgid "loading dispatchers from %s"
msgstr ""

#: ceilometer/dispatcher/__init__.py:51
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr ""

#: ceilometer/dispatcher/database.py:49
#, python-format
msgid ""
"metering data %(counter_name)s for %(resource_id)s @ %(timestamp)s: "
"%(counter_volume)s"
msgstr ""

#: ceilometer/dispatcher/database.py:68
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/database.py:71
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/energy/kwapi.py:89
msgid "Kwapi endpoint not found"
msgstr ""

#: ceilometer/event/converter.py:76
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr ""

#: ceilometer/event/converter.py:85
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:95
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr ""

#: ceilometer/event/converter.py:110
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:116
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:168
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:343
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/event/converter.py:367
#, python-format
msgid "Event Definitions configuration file: %s"
msgstr ""

#: ceilometer/event/converter.py:377
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr ""

#: ceilometer/event/converter.py:383
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr ""

#: ceilometer/event/converter.py:390
msgid "No Event Definitions configuration file found! Using default config."
msgstr ""

#: ceilometer/event/converter.py:394
#, python-format
msgid "Event Definitions: %s"
msgstr ""

#: ceilometer/event/endpoint.py:38
msgid "Loading event definitions"
msgstr ""

#: ceilometer/event/endpoint.py:64
#, python-format
msgid "Saving event \"%s\""
msgstr ""

#: ceilometer/event/endpoint.py:71
msgid "Event is not implemented with the storage backend"
msgstr ""

#: ceilometer/hardware/discovery.py:73
#, python-format
msgid "Couldn't obtain IP address ofinstance %s"
msgstr ""

#: ceilometer/hardware/plugin.py:66
msgid "Passed resource dict must contain keys resource_id and resource_url."
msgstr ""

#: ceilometer/hardware/plugin.py:108
#, python-format
msgid "inspector call failed for %(ident)s host %(host)s: %(err)s"
msgstr ""

#: ceilometer/hardware/plugin.py:139
#, python-format
msgid "Can NOT load inspector %(name)s: %(err)s"
msgstr ""

#: ceilometer/ipmi/platform/intel_node_manager.py:238
msgid "Node Manager init failed"
msgstr ""

#: ceilometer/ipmi/platform/ipmi_sensor.py:103
msgid "Wrong sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:42
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:83
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:105
msgid "ipmitool output length mismatch"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:131
msgid "running ipmitool failure"
msgstr ""

#: ceilometer/network/floatingip.py:57
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr ""

#: ceilometer/network/notifications.py:77
#, python-format
msgid "network notification %r"
msgstr ""

#: ceilometer/network/services/fwaas.py:49
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:64
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:112
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:153
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:258
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr ""

#: ceilometer/network/services/vpnaas.py:50
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:58
#: ceilometer/network/statistics/opencontrail/client.py:88
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:230
#: ceilometer/tests/network/statistics/opendaylight/test_client.py:142
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:168
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/swift.py:77
msgid "Swift endpoint not found"
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: ceilometer/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: ceilometer/openstack/common/lockutils.py:101
#, python-format
msgid "Unable to acquire lock on `%(filename)s` due to %(exception)s"
msgstr ""

#: ceilometer/openstack/common/log.py:290
#, python-format
msgid "Deprecated: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:398
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr ""

#: ceilometer/openstack/common/log.py:459
#, python-format
msgid "syslog facility must be one of: %s"
msgstr ""

#: ceilometer/openstack/common/log.py:710
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr ""

#: ceilometer/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: ceilometer/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: ceilometer/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr ""

#: ceilometer/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr ""

#: ceilometer/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: ceilometer/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: ceilometer/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: ceilometer/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: ceilometer/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: ceilometer/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: ceilometer/openstack/common/processutils.py:247
msgid "Environment not supported over SSH"
msgstr ""

#: ceilometer/openstack/common/processutils.py:251
msgid "process_input not supported over SSH"
msgstr ""

#: ceilometer/openstack/common/strutils.py:125
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr ""

#: ceilometer/openstack/common/strutils.py:230
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: ceilometer/openstack/common/strutils.py:239
#, python-format
msgid "Invalid string format: %s"
msgstr ""

#: ceilometer/publisher/file.py:63
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:77
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/messaging.py:109
#, python-format
msgid "Publishing policy set to %s, override backend retry config to 1"
msgstr ""

#: ceilometer/publisher/messaging.py:113
#, python-format
msgid "Publishing policy set to %s"
msgstr ""

#: ceilometer/publisher/messaging.py:115
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/messaging.py:168
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/messaging.py:189
#, python-format
msgid "Failed to publish %d samples, queue them"
msgstr ""

#: ceilometer/publisher/messaging.py:193
#, python-format
msgid "Failed to publish %d samples, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:59
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr ""

#: ceilometer/publisher/udp.py:66
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/__init__.py:91
#, python-format
msgid "looking for %(name)r driver in %(namespace)r"
msgstr ""

#: ceilometer/storage/impl_hbase.py:292 ceilometer/storage/impl_hbase.py:342
#, python-format
msgid "Query Resource table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:335
msgid "Pagination not implemented"
msgstr ""

#: ceilometer/storage/impl_hbase.py:383
#, python-format
msgid "Query Meter Table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:531
#: ceilometer/storage/impl_sqlalchemy.py:812
#: ceilometer/storage/pymongo_base.py:144
#, python-format
msgid "Failed to record event: %s"
msgstr ""

#: ceilometer/storage/impl_log.py:42
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr ""

#: ceilometer/storage/impl_log.py:54
#, python-format
msgid "Dropping data with TTL %d"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:308
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:376
#, python-format
msgid "%d samples removed from database"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:808
#: ceilometer/storage/pymongo_base.py:140
#, python-format
msgid "Failed to record duplicated event: %s"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:827
#, python-format
msgid "Getting events that match filter: %s"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:938
#, python-format
msgid "Get traits for %s"
msgstr ""

#: ceilometer/storage/hbase/inmemory.py:261
msgid "Opening in-memory HBase connection"
msgstr ""

#: ceilometer/storage/hbase/utils.py:439
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr ""

#: ceilometer/storage/mongo/utils.py:175
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: ceilometer/storage/mongo/utils.py:190
#: ceilometer/tests/storage/test_pymongo_base.py:206
#, python-format
msgid "Unable to connect to the database after %(retries)d retries. Giving up."
msgstr ""

#: ceilometer/storage/mongo/utils.py:194
#: ceilometer/tests/storage/test_pymongo_base.py:201
#, python-format
msgid ""
"Unable to connect to the database server: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

#: ceilometer/transformer/arithmetic.py:57
#, python-format
msgid "Arithmetic transformer must use at least one meter in expression '%s'"
msgstr ""

#: ceilometer/transformer/arithmetic.py:79
msgid "Expression evaluated to a NaN value!"
msgstr ""

#: ceilometer/transformer/arithmetic.py:95
#, python-format
msgid "Unable to evaluate expression %(expr)s: %(exc)s"
msgstr ""

#: ceilometer/transformer/arithmetic.py:109
#, python-format
msgid "Unable to perform calculation, not all of {%s} are present"
msgstr ""

#: ceilometer/transformer/conversions.py:48
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr ""

#: ceilometer/transformer/conversions.py:94
#: ceilometer/transformer/conversions.py:116
#, python-format
msgid "handling sample %s"
msgstr ""

#: ceilometer/transformer/conversions.py:97
#: ceilometer/transformer/conversions.py:137
#, python-format
msgid "converted to: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:139
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

