# Translations template for ceilometer.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the ceilometer project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: ceilometer 5.0.0.0b2.dev116\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-07-24 06:28+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: ceilometer/collector.py:125
#, python-format
msgid "UDP: Cannot decode data sent by %s"
msgstr ""

#: ceilometer/collector.py:128
#, python-format
msgid "UDP: Storing %s"
msgstr ""

#: ceilometer/collector.py:132
msgid "UDP: Unable to store meter"
msgstr ""

#: ceilometer/notification.py:185
#, python-format
msgid "Failed to load any notification handlers for %s"
msgstr ""

#: ceilometer/notification.py:201
#, python-format
msgid "Event types from %(name)s: %(type)s (ack_on_error=%(error)s)"
msgstr ""

#: ceilometer/notification.py:235
#, python-format
msgid "Pipeline endpoint: %s"
msgstr ""

#: ceilometer/pipeline.py:381
#, python-format
msgid "Unable to load publisher %s"
msgstr ""

#: ceilometer/pipeline.py:399
#, python-format
msgid ""
"Pipeline %(pipeline)s: Setup transformer instance %(name)s with parameter"
" %(param)s"
msgstr ""

#: ceilometer/pipeline.py:418 ceilometer/pipeline.py:482
#, python-format
msgid "Pipeline %(pipeline)s: Continue after error from publisher %(pub)s"
msgstr ""

#: ceilometer/pipeline.py:437
#, python-format
msgid "Pipeline %(pipeline)s: Sample dropped by transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:445
#, python-format
msgid ""
"Pipeline %(pipeline)s: Exit after error from transformer %(trans)s for "
"%(smp)s"
msgstr ""

#: ceilometer/pipeline.py:468
#, python-format
msgid "Pipeline %(pipeline)s: Transform sample %(smp)s from %(trans)s transformer"
msgstr ""

#: ceilometer/pipeline.py:498
#, python-format
msgid "Pipeline %(pipeline)s: Error flushing transformer %(trans)s"
msgstr ""

#: ceilometer/pipeline.py:663 ceilometer/pipeline.py:725
msgid "detected decoupled pipeline config format"
msgstr ""

#: ceilometer/pipeline.py:743
#, python-format
msgid "Pipeline config file: %s"
msgstr ""

#: ceilometer/pipeline.py:749 ceilometer/pipeline.py:768
#, python-format
msgid "Pipeline config: %s"
msgstr ""

#: ceilometer/pipeline.py:762
#, python-format
msgid "Polling config file: %s"
msgstr ""

#: ceilometer/service.py:103
#, python-format
msgid "%(worker_name)s value of %(workers)s is invalid, must be greater than 0"
msgstr ""

#: ceilometer/service_base.py:63
#, python-format
msgid "Pipeline has been refreshed. old hash: %(old)s, new hash: %(new)s"
msgstr ""

#: ceilometer/service_base.py:68
#, python-format
msgid "Active pipeline config's hash is %s"
msgstr ""

#: ceilometer/agent/base.py:126
#, python-format
msgid "Polling pollster %(poll)s in the context of %(src)s"
msgstr ""

#: ceilometer/agent/base.py:154
#, python-format
msgid ""
"Found following duplicated resoures for %(name)s in context of "
"%(source)s:%(list)s. Check pipeline configuration."
msgstr ""

#: ceilometer/agent/base.py:165
#, python-format
msgid "Skip polling pollster %s, no resources found"
msgstr ""

#: ceilometer/agent/base.py:188
#, python-format
msgid "Prevent pollster %(name)s for polling source %(source)s anymore!"
msgstr ""

#: ceilometer/agent/base.py:194
#, python-format
msgid "Continue after error from %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/base.py:253
#, python-format
msgid "Skip loading extension for %s"
msgstr ""

#: ceilometer/agent/base.py:257
#, python-format
msgid "Failed to import extension for %(name)s: %(error)s"
msgstr ""

#: ceilometer/agent/base.py:381
#, python-format
msgid "Unable to discover resources: %s"
msgstr ""

#: ceilometer/agent/base.py:383
#, python-format
msgid "Unknown discovery extension: %s"
msgstr ""

#: ceilometer/agent/base.py:392
msgid "Error stopping pollster."
msgstr ""

#: ceilometer/agent/plugin_base.py:70
#, python-format
msgid "Skip due to keystone error %s"
msgstr ""

#: ceilometer/agent/plugin_base.py:77
#, python-format
msgid "Skipping because %s service is not registered in keystone"
msgstr ""

#: ceilometer/alarm/rpc.py:49
#, python-format
msgid ""
"alarm %(alarm_id)s has no action configured for state transition from "
"%(previous)s to state %(state)s, skipping the notification."
msgstr ""

#: ceilometer/alarm/service.py:93
#, python-format
msgid "initiating evaluation cycle on %d alarms"
msgstr ""

#: ceilometer/alarm/service.py:98
msgid "alarm evaluation cycle failed"
msgstr ""

#: ceilometer/alarm/service.py:103
#, python-format
msgid "skipping alarm %s: type unsupported"
msgstr ""

#: ceilometer/alarm/service.py:107
#, python-format
msgid "evaluating alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:111
#, python-format
msgid "Failed to evaluate alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:179
#, python-format
msgid "Unable to parse action %(action)s for alarm %(alarm_id)s"
msgstr ""

#: ceilometer/alarm/service.py:188
#, python-format
msgid "Action %(scheme)s for alarm %(alarm_id)s is unknown, cannot notify"
msgstr ""

#: ceilometer/alarm/service.py:194
#, python-format
msgid "Notifying alarm %(id)s with action %(act)s"
msgstr ""

#: ceilometer/alarm/service.py:199
#, python-format
msgid "Unable to notify alarm %s"
msgstr ""

#: ceilometer/alarm/service.py:220
msgid "Unable to notify for an alarm with no action"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:75
#, python-format
msgid "alarm %(id)s transitioning to %(state)s because %(reason)s"
msgstr ""

#: ceilometer/alarm/evaluator/__init__.py:87
msgid "alarm state update failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:36
msgid "alarm retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:57
#, python-format
msgid "Alarms %(alarm_ids)s are in unknown state"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:79
#, python-format
msgid "Transition to %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:83
#, python-format
msgid "Remaining as %(state)s due to alarms %(alarm_ids)s in state %(state)s"
msgstr ""

#: ceilometer/alarm/evaluator/combination.py:104
#: ceilometer/alarm/evaluator/gnocchi.py:214
#: ceilometer/alarm/evaluator/threshold.py:178
#, python-format
msgid "Attempted to evaluate alarm %s, but it is not within its time constraint."
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:106
#: ceilometer/alarm/evaluator/threshold.py:89
#, python-format
msgid "stats query %s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:110
#: ceilometer/alarm/evaluator/threshold.py:95
msgid "alarm stats retrieval failed"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:113
#, python-format
msgid "alarm stats retrieval failed: %s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:128
#: ceilometer/alarm/evaluator/threshold.py:56
#, python-format
msgid "query stats from %(start)s to %(now)s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:140
#: ceilometer/alarm/evaluator/threshold.py:112
#, python-format
msgid "%d datapoints are unknown"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:163
#: ceilometer/alarm/evaluator/threshold.py:137
#, python-format
msgid ""
"Transition to %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:167
#: ceilometer/alarm/evaluator/threshold.py:141
#, python-format
msgid ""
"Remaining as %(state)s due to %(count)d samples %(disposition)s "
"threshold, most recent: %(most_recent)s"
msgstr ""

#: ceilometer/alarm/evaluator/gnocchi.py:226
#: ceilometer/alarm/evaluator/threshold.py:197
#, python-format
msgid "comparing value %(value)s against threshold %(limit)s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:66
#, python-format
msgid "sanitize stats %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:75
#, python-format
msgid "excluded weak datapoints with sample counts %s"
msgstr ""

#: ceilometer/alarm/evaluator/threshold.py:84
#, python-format
msgid "pruned statistics to %d"
msgstr ""

#: ceilometer/alarm/notifier/log.py:31
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s of %(severity)s priority from"
" %(previous)s to %(current)s with action %(action)s because %(reason)s."
msgstr ""

#: ceilometer/alarm/notifier/rest.py:64
#, python-format
msgid ""
"Notifying alarm %(alarm_name)s %(alarm_id)s with severity %(severity)s "
"from %(previous)s to %(current)s with action %(action)s because "
"%(reason)s. request-id: %(request_id)s "
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:87
#: ceilometer/event/storage/impl_hbase.py:80
#: ceilometer/storage/impl_hbase.py:131
msgid "Dropping HBase schema..."
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:94
#: ceilometer/event/storage/impl_hbase.py:86
#: ceilometer/storage/impl_hbase.py:138
msgid "Cannot disable table but ignoring error"
msgstr ""

#: ceilometer/alarm/storage/impl_hbase.py:98
#: ceilometer/event/storage/impl_hbase.py:90
#: ceilometer/storage/impl_hbase.py:142
msgid "Cannot delete table but ignoring error"
msgstr ""

#: ceilometer/alarm/storage/models.py:70
msgid "timestamp should be datetime object"
msgstr ""

#: ceilometer/alarm/storage/models.py:72
msgid "state_timestamp should be datetime object"
msgstr ""

#: ceilometer/api/app.py:135
#, python-format
msgid "Starting server in PID %s"
msgstr ""

#: ceilometer/api/app.py:136
msgid "Configuration:"
msgstr ""

#: ceilometer/api/app.py:140
#, python-format
msgid "serving on 0.0.0.0:%(sport)s, view at http://127.0.0.1:%(vport)s"
msgstr ""

#: ceilometer/api/app.py:144
#, python-format
msgid "serving on http://%(host)s:%(port)s"
msgstr ""

#: ceilometer/api/middleware.py:109
#, python-format
msgid "Error parsing HTTP response: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:91
#, python-format
msgid "Alarm quota exceeded for user %(u)s on project %(p)s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:173
#, python-format
msgid "Timezone %s is not valid"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:288
msgid "Time constraint names must be unique for a given alarm."
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:298
#, python-format
msgid "%(rule)s must be set for %(type)s type alarm"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:309
#, python-format
msgid "%(rule1)s and %(rule2)s cannot be set at the same time"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:325
#, python-format
msgid "duplicate actions are found: %s, remove duplicate ones"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:331
#, python-format
msgid "%(name)s count exceeds maximum value %(maximum)d"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:342
#, python-format
msgid "Unable to parse action %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:345
#, python-format
msgid "Unsupported action %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:348
#, python-format
msgid "You are not authorized to create action: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:584
#, python-format
msgid "Alarm with name=%s exists"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:596
#, python-format
msgid "Error while putting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:597
#: ceilometer/api/controllers/v2/alarms.py:766
msgid "Alarm incorrect"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:657
msgid "state invalid"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:759
#, python-format
msgid "Alarm with name='%s' exists"
msgstr ""

#: ceilometer/api/controllers/v2/alarms.py:765
#, python-format
msgid "Error while posting alarm: %s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:50
#, python-format
msgid "%(entity)s %(id)s Not Found"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:59
#, python-format
msgid "Not Authorized to access %(aspect)s %(id)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:220
#, python-format
msgid "Unable to convert the value %(value)s to the expected data type %(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:225
#, python-format
msgid ""
"The data type %(type)s is not supported. The supported data type list is:"
" %(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:230
#, python-format
msgid ""
"Unexpected exception converting %(value)s to the expected data type "
"%(type)s."
msgstr ""

#: ceilometer/api/controllers/v2/base.py:240
#, python-format
msgid "Alarm %s not found"
msgstr ""

#: ceilometer/api/controllers/v2/base.py:242
#, python-format
msgid "Alarm %(alarm_id)s not found in project %(project)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:172
#, python-format
msgid ""
"operator %(operator)s is not supported. the supported operators are: "
"%(supported)s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:197
#, python-format
msgid "Getting traits for %s"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:271
msgid "Event"
msgstr ""

#: ceilometer/api/controllers/v2/events.py:274
#, python-format
msgid "More than one event with id %s returned from storage driver"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:184
msgid "clamping min timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:189
msgid "clamping max timestamp to range"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:308
msgid "Samples should be included in request body"
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:393
msgid "Period must be positive."
msgstr ""

#: ceilometer/api/controllers/v2/meters.py:422
#, python-format
msgid "Invalid period %(period)s: %(err)s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:204
#, python-format
msgid "Filter expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:219
#, python-format
msgid "Order-by expression not valid: %s"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:229
msgid "Limit should be positive"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:321
#, python-format
msgid "String %s is not a valid isotime"
msgstr ""

#: ceilometer/api/controllers/v2/query.py:322
#, python-format
msgid "Failed to parse the timestamp value %s"
msgstr ""

#: ceilometer/api/controllers/v2/resources.py:128
msgid "Resource"
msgstr ""

#: ceilometer/api/controllers/v2/samples.py:144
msgid "Sample"
msgstr ""

#: ceilometer/api/controllers/v2/utils.py:50
msgid "Limit must be positive"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:39
#, python-format
msgid "Combined state of alarms %s"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:48
msgid "Alarm combination rule should contain at least two different alarm ids."
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/combination.py:69
#, python-format
msgid "Cannot specify alarm %s itself in combination rule"
msgstr ""

#: ceilometer/api/controllers/v2/alarm_rules/threshold.py:93
#, python-format
msgid ""
"Alarm when %(meter_name)s is %(comparison_operator)s a %(statistic)s of "
"%(threshold)s over %(period)s seconds"
msgstr ""

#: ceilometer/cmd/eventlet/storage.py:40
msgid "Clearing expired metering data"
msgstr ""

#: ceilometer/cmd/eventlet/storage.py:49
msgid "Clearing expired event data"
msgstr ""

#: ceilometer/compute/notifications/cpu.py:51
#, python-format
msgid "An error occurred while building %(m)s sample: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:33
#, python-format
msgid "checking instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:36
#, python-format
msgid "CPUTIME USAGE: %(instance)s %(time)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:50
#: ceilometer/compute/pollsters/cpu.py:81
#: ceilometer/compute/pollsters/disk.py:131
#: ceilometer/compute/pollsters/disk.py:341
#: ceilometer/compute/pollsters/disk.py:523
#: ceilometer/compute/pollsters/disk.py:604
#: ceilometer/compute/pollsters/disk.py:699
#: ceilometer/compute/pollsters/memory.py:49
#: ceilometer/compute/pollsters/memory.py:92
#: ceilometer/compute/pollsters/net.py:106
#, python-format
msgid "Exception while getting samples %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:53
#, python-format
msgid "Obtaining CPU time is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:56
#, python-format
msgid "could not get CPU time for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:65
#, python-format
msgid "Checking CPU util for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:69
#, python-format
msgid "CPU UTIL: %(instance)s %(util)d"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:84
#, python-format
msgid "Obtaining CPU Util is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/cpu.py:87
#, python-format
msgid "Could not get CPU Util for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:139
#: ceilometer/compute/pollsters/disk.py:344
#: ceilometer/compute/pollsters/disk.py:526
#: ceilometer/compute/pollsters/disk.py:707
#: ceilometer/compute/pollsters/net.py:114
#, python-format
msgid "%(inspector)s does not provide data for  %(pollster)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:144
#: ceilometer/compute/pollsters/disk.py:350
#: ceilometer/compute/pollsters/disk.py:532
#: ceilometer/compute/pollsters/disk.py:613
#: ceilometer/compute/pollsters/net.py:119
#, python-format
msgid "Ignoring instance %(name)s: %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:607
#, python-format
msgid "%(inspector)s does not provide data for %(pollster)s"
msgstr ""

#: ceilometer/compute/pollsters/disk.py:713
#, python-format
msgid "Ignoring instance %(name)s (%(instance_id)s) : %(error)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:33
#, python-format
msgid "Checking memory usage for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:37
#, python-format
msgid "MEMORY USAGE: %(instance)s %(usage)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:62
#, python-format
msgid "Obtaining Memory Usage is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:65
#, python-format
msgid "Could not get Memory Usage for %(id)s: %(e)s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:75
#, python-format
msgid "Checking resident memory for instance %s"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:80
#, python-format
msgid "RESIDENT MEMORY: %(instance)s %(resident)f"
msgstr ""

#: ceilometer/compute/pollsters/memory.py:105
#, python-format
msgid "Obtaining Resident Memory is not implemented for %s"
msgstr ""

#: ceilometer/compute/pollsters/net.py:92
#, python-format
msgid "checking net info for instance %s"
msgstr ""

#: ceilometer/compute/virt/inspector.py:291
#, python-format
msgid "Unable to load the hypervisor inspector: %s"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:223
#, python-format
msgid "VM %s not found on Hyper-V"
msgstr ""

#: ceilometer/compute/virt/hyperv/utilsv2.py:225
#, python-format
msgid "Duplicate VM name found: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:54
msgid "Connection to libvirt broken"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:79
#, python-format
msgid "Connecting to libvirt: %s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:97
#, python-format
msgid ""
"Error from libvirt while looking up instance <name=%(name)s, id=%(id)s>: "
"[Error Code %(error_code)s] %(ex)s"
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:117
#, python-format
msgid ""
"Failed to inspect data of instance <name=%(name)s, id=%(id)s>, domain "
"state is SHUTOFF."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:187
#, python-format
msgid ""
"Failed to inspect memory usage of instance <name=%(name)s, id=%(id)s>, "
"can not get info from libvirt."
msgstr ""

#: ceilometer/compute/virt/libvirt/inspector.py:195
#, python-format
msgid ""
"Failed to inspect memory usage of %(instance_uuid)s, can not get info "
"from libvirt: %(error)s"
msgstr ""

#: ceilometer/compute/virt/vmware/inspector.py:106
#: ceilometer/compute/virt/vmware/inspector.py:123
#: ceilometer/compute/virt/vmware/inspector.py:155
#: ceilometer/compute/virt/vmware/inspector.py:168
#, python-format
msgid "VM %s not found in VMware vSphere"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:57
msgid "XenAPI not installed"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:63
msgid "Must specify connection_url, and connection_password to use"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:66
msgid "Unable to log in to XenAPI (is the Dom0 disk full?)"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:73
#, python-format
msgid "Could not connect to XenAPI: %s"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:96
#, python-format
msgid "VM %s not found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:99
#, python-format
msgid "Multiple VM %s found in XenServer"
msgstr ""

#: ceilometer/compute/virt/xenapi/inspector.py:112
#, python-format
msgid "Could not get VM %s CPU Utilization"
msgstr ""

#: ceilometer/dispatcher/__init__.py:41
#, python-format
msgid "loading dispatchers from %s"
msgstr ""

#: ceilometer/dispatcher/__init__.py:52
#, python-format
msgid "Failed to load any dispatchers for %s"
msgstr ""

#: ceilometer/dispatcher/database.py:76 ceilometer/dispatcher/http.py:89
#, python-format
msgid ""
"metering data %(counter_name)s for %(resource_id)s @ %(timestamp)s: "
"%(counter_volume)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:56
msgid "The Yaml file that defines per metric archive policies."
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:141
msgid "No archive policy file found! Using default config."
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:311
#, python-format
msgid ""
"The metric %(metric_name)s of resource %(resource_id)s doesn't exists: "
"%(status_code)d"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:320
#, python-format
msgid ""
"Fail to post measure on metric %(metric_name)s of resource "
"%(resource_id)s with status: %(status_code)d: %(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:343
#, python-format
msgid ""
"Resource %(resource_id)s creation failed with status: %(status_code)d: "
"%(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:361
#, python-format
msgid ""
"Resource %(resource_id)s update failed with status: %(status_code)d: "
"%(msg)s"
msgstr ""

#: ceilometer/dispatcher/gnocchi.py:383
#, python-format
msgid ""
"Fail to create metric %(metric_name)s of resource %(resource_id)s with "
"status: %(status_code)d: %(msg)s"
msgstr ""

#: ceilometer/dispatcher/http.py:79
msgid ""
"Dispatcher target was not set, no meter will be posted. Set the target in"
" the ceilometer.conf file"
msgstr ""

#: ceilometer/dispatcher/http.py:114
#, python-format
msgid "Message posting finished with status code %d."
msgstr ""

#: ceilometer/dispatcher/http.py:117
#, python-format
msgid "Failed to record metering data: %s"
msgstr ""

#: ceilometer/dispatcher/http.py:120
#, python-format
msgid "message signature invalid, discarding message: %r"
msgstr ""

#: ceilometer/energy/kwapi.py:88
msgid "Kwapi endpoint not found"
msgstr ""

#: ceilometer/event/converter.py:78
#, python-format
msgid "Plugin specified, but no plugin name supplied for trait %s"
msgstr ""

#: ceilometer/event/converter.py:87
#, python-format
msgid "No plugin named %(plugin)s available for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:97
#, python-format
msgid "Required field in trait definition not specified: '%s'"
msgstr ""

#: ceilometer/event/converter.py:112
#, python-format
msgid ""
"Parse error in JSONPath specification '%(jsonpath)s' for %(trait)s: "
"%(err)s"
msgstr ""

#: ceilometer/event/converter.py:118
#, python-format
msgid "Invalid trait type '%(type)s' for trait %(trait)s"
msgstr ""

#: ceilometer/event/converter.py:171
#, python-format
msgid "Required field %s not specified"
msgstr ""

#: ceilometer/event/converter.py:348
#, python-format
msgid "Dropping Notification %(type)s (uuid:%(msgid)s)"
msgstr ""

#: ceilometer/event/converter.py:372
#, python-format
msgid "Event Definitions configuration file: %s"
msgstr ""

#: ceilometer/event/converter.py:382
#, python-format
msgid ""
"Invalid YAML syntax in Event Definitions file %(file)s at line: %(line)s,"
" column: %(column)s."
msgstr ""

#: ceilometer/event/converter.py:388
#, python-format
msgid "YAML error reading Event Definitions file %(file)s"
msgstr ""

#: ceilometer/event/converter.py:395
msgid "No Event Definitions configuration file found! Using default config."
msgstr ""

#: ceilometer/event/converter.py:399
#, python-format
msgid "Event Definitions: %s"
msgstr ""

#: ceilometer/event/endpoint.py:33
msgid "Loading event definitions"
msgstr ""

#: ceilometer/hardware/discovery.py:74
#, python-format
msgid "Couldn't obtain IP address of instance %s"
msgstr ""

#: ceilometer/hardware/plugin.py:67
msgid "Passed resource dict must contain keys resource_id and resource_url."
msgstr ""

#: ceilometer/hardware/plugin.py:109
#, python-format
msgid "inspector call failed for %(ident)s host %(host)s: %(err)s"
msgstr ""

#: ceilometer/hardware/plugin.py:140
#, python-format
msgid "Can NOT load inspector %(name)s: %(err)s"
msgstr ""

#: ceilometer/ipmi/platform/intel_node_manager.py:300
msgid "Node Manager init failed"
msgstr ""

#: ceilometer/ipmi/platform/ipmi_sensor.py:101
msgid "Wrong sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:39
msgid "parse IPMI sensor data failed,unknown sensor type"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:80
msgid "parse IPMI sensor data failed,No data retrieved from given input"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:102
msgid "ipmitool output length mismatch"
msgstr ""

#: ceilometer/ipmi/platform/ipmitool.py:128
msgid "running ipmitool failure"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:66
#, python-format
msgid "Polling %(name)s faild for %(cnt)s times!"
msgstr ""

#: ceilometer/ipmi/pollsters/node.py:71 ceilometer/ipmi/pollsters/sensor.py:74
#, python-format
msgid "Pollster for %s is disabled!"
msgstr ""

#: ceilometer/ipmi/pollsters/sensor.py:68
#, python-format
msgid "Polling %(mtr)s sensor failed for %(cnt)s times!"
msgstr ""

#: ceilometer/network/floatingip.py:54
#, python-format
msgid "FLOATING IP USAGE: %s"
msgstr ""

#: ceilometer/network/services/fwaas.py:48
#, python-format
msgid "Unknown status %(stat)s received on fw %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:62
#, python-format
msgid "Unknown status %(stat)s received on pool %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:110
#, python-format
msgid "Unknown status %(stat)s received on vip %(id)s, skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:151
#, python-format
msgid "Unknown status %(stat)s received on member %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/services/lbaas.py:256
#, python-format
msgid "Ignoring pool %(pool_id)s: %(error)s"
msgstr ""

#: ceilometer/network/services/vpnaas.py:49
#, python-format
msgid "Unknown status %(stat)s received on vpn %(id)s,skipping sample"
msgstr ""

#: ceilometer/network/statistics/opencontrail/client.py:58
#, python-format
msgid "Opencontrail API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/client.py:232
#: ceilometer/tests/network/statistics/opendaylight/test_client.py:142
#, python-format
msgid "OpenDaylitght API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/network/statistics/opendaylight/driver.py:169
msgid "Request failed to connect to OpenDaylight with NorthBound REST API"
msgstr ""

#: ceilometer/objectstore/rgw.py:79
msgid "Radosgw endpoint not found"
msgstr ""

#: ceilometer/objectstore/rgw_client.py:48
#, python-format
msgid "RGW AdminOps API returned %(status)s %(reason)s"
msgstr ""

#: ceilometer/objectstore/swift.py:76
msgid "Swift endpoint not found"
msgstr ""

#: ceilometer/publisher/file.py:62
msgid "The path for the file publisher is required"
msgstr ""

#: ceilometer/publisher/file.py:76
msgid "max_bytes and backup_count should be numbers."
msgstr ""

#: ceilometer/publisher/messaging.py:88
#, python-format
msgid "Publishing policy set to %s"
msgstr ""

#: ceilometer/publisher/messaging.py:90
#, python-format
msgid "Publishing policy is unknown (%s) force to default"
msgstr ""

#: ceilometer/publisher/messaging.py:143
#, python-format
msgid "Publisher max local_queue length is exceeded, dropping %d oldest samples"
msgstr ""

#: ceilometer/publisher/messaging.py:154
#, python-format
msgid "Failed to publish %d datapoints, queue them"
msgstr ""

#: ceilometer/publisher/messaging.py:158
#, python-format
msgid "Failed to publish %d datapoints, dropping them"
msgstr ""

#: ceilometer/publisher/udp.py:60
#, python-format
msgid "Publishing sample %(msg)s over UDP to %(host)s:%(port)d"
msgstr ""

#: ceilometer/publisher/udp.py:67
msgid "Unable to send sample over UDP"
msgstr ""

#: ceilometer/storage/impl_hbase.py:215 ceilometer/storage/impl_hbase.py:266
#, python-format
msgid "Query Resource table: %s"
msgstr ""

#: ceilometer/storage/impl_hbase.py:308
#, python-format
msgid "Query Meter Table: %s"
msgstr ""

#: ceilometer/storage/impl_log.py:41
#, python-format
msgid "metering data %(counter_name)s for %(resource_id)s: %(counter_volume)s"
msgstr ""

#: ceilometer/storage/impl_log.py:53
#, python-format
msgid "Dropping metering data with TTL %d"
msgstr ""

#: ceilometer/storage/impl_mongodb.py:557
msgid ""
"Clearing expired metering data is based on native MongoDB time to live "
"feature and going in background."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:306
#, python-format
msgid "Unknown metadata type. Key (%s) will not be queryable."
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:362
#, python-format
msgid "%d samples removed from database"
msgstr ""

#: ceilometer/storage/impl_sqlalchemy.py:381
msgid "Expired residual resource and meter definition data"
msgstr ""

#: ceilometer/storage/hbase/base.py:45
msgid "Creating a new in-memory HBase Connection object"
msgstr ""

#: ceilometer/storage/hbase/base.py:62
#, python-format
msgid "connecting to HBase on %(host)s:%(port)s"
msgstr ""

#: ceilometer/storage/hbase/inmemory.py:268
msgid "Opening in-memory HBase connection"
msgstr ""

#: ceilometer/storage/hbase/utils.py:474
#, python-format
msgid "Cannot create table %(table_name)s   it already exists. Ignoring error"
msgstr ""

#: ceilometer/storage/mongo/utils.py:248
#, python-format
msgid "Connecting to %(db)s on %(nodelist)s"
msgstr ""

#: ceilometer/storage/mongo/utils.py:263
#, python-format
msgid "Unable to connect to the database server: %(errmsg)s."
msgstr ""

#: ceilometer/storage/mongo/utils.py:402
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb after %(retries)d retries. "
"Giving up."
msgstr ""

#: ceilometer/storage/mongo/utils.py:406
#, python-format
msgid ""
"Unable to reconnect to the primary mongodb: %(errmsg)s. Trying again in "
"%(retry_interval)d seconds."
msgstr ""

#: ceilometer/transformer/arithmetic.py:55
#, python-format
msgid "Arithmetic transformer must use at least one meter in expression '%s'"
msgstr ""

#: ceilometer/transformer/arithmetic.py:77
msgid "Expression evaluated to a NaN value!"
msgstr ""

#: ceilometer/transformer/arithmetic.py:93
#, python-format
msgid "Unable to evaluate expression %(expr)s: %(exc)s"
msgstr ""

#: ceilometer/transformer/arithmetic.py:107
#, python-format
msgid "Unable to perform calculation, not all of {%s} are present"
msgstr ""

#: ceilometer/transformer/conversions.py:46
#, python-format
msgid "scaling conversion transformer with source: %(source)s target: %(target)s:"
msgstr ""

#: ceilometer/transformer/conversions.py:92
#: ceilometer/transformer/conversions.py:114
#, python-format
msgid "handling sample %s"
msgstr ""

#: ceilometer/transformer/conversions.py:95
#: ceilometer/transformer/conversions.py:135
#, python-format
msgid "converted to: %s"
msgstr ""

#: ceilometer/transformer/conversions.py:137
#, python-format
msgid "dropping sample with no predecessor: %s"
msgstr ""

